### PR TITLE
📌 explicit latest versions

### PR DESCRIPTION
**Pull request by vinicius73**
* Target version: master 

### Summary

Just make explicit we are using the updated versions of dependencies.

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Sure, I guess dependabot would bump them anyways with future bumps then to be in sync...

**Review by mejo- — APPROVED** [review]

**Comment by vinicius73** [comment]
> Sure, I guess dependabot would bump them anyways with future bumps then to be in sync...

We can use `versioning-strategy: increase`, looks like it will do what we are talking about.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

**Pull request merged**
