### PR TITLE
Use file.path to track EditorWrapper instances more accurately

### PR DESCRIPTION
**Pull request by artonge**
This fixes rich workspace loading when moving a `Readme.md` into a folder and navigating into that folder.

The `file.id` stays the same, so no new components are created and RichWorkspace stays in a `ready=false` state because EditorWrapper never emits a new ready event.

### CODE REVIEW

**Review by eneiluj — APPROVED** [review]
:+1: Nice catch

**Comment by eneiluj** [comment]
Rebased and recompiled

**Comment by mejo-** [comment]
Sorry rebased, compiled and force-pushed another time.

**Review by mejo- — APPROVED** [review]

**Pull request merged**
