### PR TITLE
ViewerComponent: pass on autofocus to EditorWrapper

### PR DESCRIPTION
**Pull request by azul**
The `ViewerComponent` is reused in the collectives app.
Allow disabling autofocus when using the viewer component.

* Resolves: # 
* Target version: master, 21, 20

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Hm, where has the node check gone :/

**Comment by juliushaertl** [comment]
Ah it only runs on push which is then probably not happening on a fork.

@azul Could you build and commit the updated bundles as well?

**Comment by azul** [comment]
@juliushaertl like so?

**Comment by juliushaertl** [comment]
Yes, looks good :+1:

**Pull request merged**
