### PR TITLE
🐛 fix viewer integration styling

### PR DESCRIPTION
**Pull request by vinicius73**
* Resolves: #2371
* Reference: https://github.com/nextcloud/viewer/pull/1229
* Target version: master 

Before

image

After

image

### CODE REVIEW

**Comment by szaimen** [comment]
How does it look on mobile?

**Comment by juliushaertl** [comment]
Screenshot 2022-05-09 at 08 11 54

Now I have a black bar at the bottom ;)

**Comment by szaimen** [comment]
> > How does it look on mobile?
> 
> @szaimen
> 
> image

looks good, thanks! However some icons are missing?

**Comment by vinicius73** [comment]
Looks related to #2374 @szaimen

**Comment by szaimen** [comment]
> Looks related to #2374 @szaimen

yes indeed but I meant these:
image

**Comment by vinicius73** [comment]
Nothing wrong @szaimen 

It is intentional, from #2294 

image

**Comment by szaimen** [comment]
> Nothing wrong @szaimen
> 
> It is intentional, from #2294
> 
> image

Ah okay, great! :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
