### PR TITLE
fix(a11y): contrast for active menubar buttons

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

* Resolves: #5065 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
grafik | grafik

Dropdown menus (headings and callouts) are still low contrast:

grafik

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- we do not test UI look yet.
- documentation is not required.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Thinking more about the dropdown, maybe it is already fine like it is as the primary trigger button already indicates the state?

**Comment by max-nextcloud** [comment]
> Thinking more about the dropdown, maybe it is already fine like it is as the primary trigger button already indicates the state?

I'd be happy to merge this as is as a start and then discuss how to continue.

**Comment by szaimen** [comment]
> * On light mode the color does not seem to fit.
Changing https://github.com/nextcloud/text/blob/e1afbfec13d446f53dbe79f4179fbd584a14c43d/src/components/Menu/ActionEntry.scss#L47 to `fill: var(--color-primary-element-text)` should most likely fix it

**Comment by max-nextcloud** [comment]
> And I'm wondering if we shall give those a gap of 2px to make it look a bit nicer when two besides each other are active?

grafik

**Review by szaimen — APPROVED** [review]
LGTM from the screenshots but didnt test.

Maybe we should loop in Frank because it is kind of a drastic design change again?

**Comment by max-nextcloud** [comment]
> Maybe we should loop in Frank because it is kind of a drastic design change again?

Let's check with @jancborchardt then.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Cypress failures seem related

**Comment by max-nextcloud** [comment]
> Cypress failures seem related

I think the failure on runner 3 actually is related.
Mobile actions -- formatting modal help (failed)


Due to the larger spacing between buttons the `more` button is overlapped.

**Comment by max-nextcloud** [comment]
Removed the padding on mobile views (<768 according to texts definition).

[Bildschirmaufzeichnung vom 21.12.2023, 08:11:03.webm](https://github.com/nextcloud/text/assets/97337118/11700d81-b75d-4a91-8ca4-aa42ab37c41e)

**Review by JuliaKirschenheuter — APPROVED** [review]
looks good, thanks a lot!

**Comment by max-nextcloud** [comment]
Cypress tests are still failing and the failure seems to be related.

**Pull request merged**
