### PR TITLE
test(cy): rely on @nextcloud/axios for requests

### PR DESCRIPTION
**Pull request by max-nextcloud**
Simplify the handling of csrf-tokens and auth.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- Simplifying tests.
- No documentation needed.

### CODE REVIEW

**Comment by max-nextcloud** [comment]
I have no idea why this is not running the cypress tests. Somehow the initial job does not seem to get started.

**Comment by max-nextcloud** [comment]
Currently crashes the browser for me when running cypress test for direct editing. I think we've seen that as well when testing a cypress upgrade. Will set to draft until I manage to resolve it.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Very nice cleanup 🚀

**Pull request merged**
