### PR TITLE
Use the href of links for link previews, not `node.textContent`

### PR DESCRIPTION
**Pull request by mejo-**
Until now we used node.textContent to determine whether a paragraph is a link that warrants a link preview. Instead, we now check whether the paragraph has a single text node wich is a link and use its href.

Text nodes with empty textContent are ignored in order to allow whitespaces before and after the link.

This way we ensure to always show the preview of the link target, not of the description text. Both may differ, which has security implications.

Also, links with a custom description get a link preview as well.

And last but not least, it fixes link previes for URLs with spaces. (Background: for some reason, url-encoded spaces in textContent of links get decoded when they're transformed to markdown and written to a file. Therefore URLs with spaces lost their link preview once the Text session was closed prior to this commit)

Fixes: #3871

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Nice, thanks for the quick fixing :)

**Comment by mejo-** [comment]
/backport 35db3d4d96f8bd68be07ef3da8d59d00f181c61f to stable25

**Pull request merged**
