### PR TITLE
fix(sync): handle 502 (Bad Gateway) gracefully

### PR DESCRIPTION
**Pull request by max-nextcloud**
This is the proxies response when the request to the server fails.
It is often temporary - so it makes sense to keep trying.

Without this text will stop fetching changes from the server
on the first 502 it encounters.

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by max-nextcloud** [comment]
cypress failures are unrelated.

**Comment by juliushaertl** [comment]
Nice one :)

**Pull request merged**
