### PR TITLE
Widget fixes

### PR DESCRIPTION
**Pull request by juliushaertl**
- fix: Limit paragraph spacing to the content
- fix: Only attempt to show reference widgets for logged in users

### 📝 Summary

Avoid rendering issues with reference previews on paragraphs and public share links.

### CODE REVIEW

**Review by mejo- — COMMENTED** [review]
Code looks good to me.

**Review by mejo- — APPROVED** [review]

**Comment by mejo-** [comment]
I wonder though why the Node CI job didn't fail - this PR contains changes to the JS sources that should require a compile, no? :thinking:

**Comment by juliushaertl** [comment]
Indeed, I first had suspected https://github.com/nextcloud/.github/issues/124 but we only have js/scss files here.

**Comment by juliushaertl** [comment]
Ah I think it is because css/* changes are also not part of the path checks for node. :/

**Pull request merged**
