### PR TITLE
⬆️ Upgrade dependencies

### PR DESCRIPTION
**Pull request by vinicius73**

### CODE REVIEW

**Comment by eneiluj** [comment]
We get this error when inserting an image (upload or local). Seems like an issue when chaining operations:
image

**Comment by vinicius73** [comment]
@eneiluj I've run `npm dedup` and it fixes the problem.
It seems we have 2 versions of `linkifyjs`

```
├─┬ @nextcloud/vue@7.0.0-beta.6
│ └─┬ linkify-string@4.0.0
│   └── linkifyjs@4.0.1
└─┬ @tiptap/extension-link@2.0.0-beta.199
  └── linkifyjs@3.0.5
```

**Review by eneiluj — APPROVED** [review]
:boom:

**Comment by vinicius73** [comment]
/backport 1d49a82fe88548d585e840a60886dfa690246fb3,1d49a82fe88548d585e840a60886dfa690246fb3,4dd0d93719072e72182b48792b6f25acaa2052f6 to stable25

**Comment by juliushaertl** [comment]
@vinicius73 Mind to manually backport the cypress changes?

**Comment by juliushaertl** [comment]
Relevant commit back ported with https://github.com/nextcloud/text/pull/3206

**Pull request merged**
