### PR TITLE
Use import from esm to avoid duplication

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

### 📝 Summary

Do not import individual dist assets from `@nextcloud/vue` to avoid code duplication in our bundles

Should save at least 421KB according to https://app.relative-ci.com/projects/bk4uOndp0VBDu0zgKtyn/jobs/492-z24TCHpLgZBq2riUXFcL/compare/226-RjgmU4dFEfuoHwJ2Ki5u/modules

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/master/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
Looks good. Great to see the bundle size go down. :smiley:

**Comment by juliushaertl** [comment]
No backport needed as e286194c690c15c5d66b3a7198ee76b9366f1201 was only introduced on master

**Pull request merged**
