### PR TITLE
Allow to scroll tables horizontally

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #2412

#### 🖼️ Screencast

[recording.webm](https://user-images.githubusercontent.com/3582805/223554603-605a902f-a9d4-4e3b-98dd-dd24fb01f449.webm)

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
Manual backport to stable25: https://github.com/nextcloud/text/pull/3938

**Pull request merged**
