### PR TITLE
Block file access for secure view

### PR DESCRIPTION
**Pull request by juliushaertl**
Addresses the prevent download share permission added with https://github.com/nextcloud/server/pull/32482

For now we block access through text fully

Screenshot 2022-08-03 at 12 51 29

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
Code looks good.
I think it would be good to have this covered with a test:
* It's hard to test by hand as it seems to involve issueing a curl request to remove the download permission as outlined in the linked server PR.
* It has security relevance
* We might break it accidentally at some point because it's a corner case we don't remember.

**Comment by juliushaertl** [comment]
Rebased and pushed a small cypress test.

**Review by max-nextcloud — APPROVED** [review]
Nice one! Thanks for adding the test.

**Comment by max-nextcloud** [comment]
/backport af55553256a3cbc1fec31e7b4c7bbcdd6f9fa274 7d913cfec536a8f9b598affc18e96aa9df63e7e0 to stable24

**Comment by max-nextcloud** [comment]
/backport af55553256a3cbc1fec31e7b4c7bbcdd6f9fa274 7d913cfec536a8f9b598affc18e96aa9df63e7e0 to stable25

**Comment by max-nextcloud** [comment]
/backport af55553256a3cbc1fec31e7b4c7bbcdd6f9fa274 to stable24

**Comment by max-nextcloud** [comment]
/backport af55553256a3cbc1fec31e7b4c7bbcdd6f9fa274 to stable25

**Pull request merged**
