### PR TITLE
Adjust smart picker menu action

### PR DESCRIPTION
**Pull request by julien-nc**
* Adjust the menu item label
* Adjust the icon to use the same as in Mail

### CODE REVIEW

**Comment by julien-nc** [comment]
IMO this can be backported to stable26 but this is not a bug fix...

**Review by max-nextcloud — APPROVED** [review]

**Comment by max-nextcloud** [comment]
> IMO this can be backported to stable26 but this is not a bug fix...

I'll create a backport request. Stable26 is blocked for most of the week anyway and we can discuss if we want to backport in the backport PR.

**Pull request merged**
