### PR TITLE
Add dependabot config for stable branches

### PR DESCRIPTION
**Pull request by juliushaertl**

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
I'm not 100% sure about the `versioning-strategy: lockfile-only`
We'll have to try, I don't remember

**Comment by juliushaertl** [comment]
Same here from the docs, let's see.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/text/network/updates

Capture d’écran_2020-11-09_09-14-45

**Comment by skjnldsv** [comment]
```
Dependabot cannot open any more pull requests as the open pull request limit has been exceeded. The current limit is: 10.

Dependabot will open new pull requests once you merge or close the already open pull requests. You can also update this limit in the config file.

```

Ah

**Comment by PVince81** [comment]
and most cannot be merged, seems there is a failing test with timeout, for example https://github.com/nextcloud/text/pull/1143/checks?check_run_id=1373003272

**Comment by PVince81** [comment]
seems this was broken since a while, even here transifex fail on master: https://github.com/nextcloud/text/actions/runs/338703353

**Pull request merged**
