### PR TITLE
Fix: relative link in RichWorkspace

### PR DESCRIPTION
**Pull request by vinicius73**
## To reproduce:

- Create a folder A
- Create a folder B inside the folder A
- Create a `demo.md` file inside folder B
- Create an `Readme.md` file in the folder A
- In Rich Workspace, create a link to an inline file in `/A/B/demo.md` 
- Try to open this link

## Expected behavior

The rich workspace must open `/A/B/demo.md` instead of `/B/demo.md`.

### CODE REVIEW

**Comment by mejo-** [comment]
/backport 403fe2e179c56c6b672f480d4392484e7aac8d51,0c534433236b575c16e209b2314c48c18a7a128c to stable25

**Comment by vinicius73** [comment]
backport must be done manually @mejo-, since link feature have changed in #2665

**Comment by mejo-** [comment]
Ah, sorry @vinicius73. The backport of the two commits was successful though: #3323. Feel free to take over :blush:

**Pull request merged**
