### PR TITLE
Don't show "Link file" button when using direct edition

### LINKED ISSUE #1975: "Link file" button is displayed in Android client
"Link file" button is displayed when selecting some text in NC Android client. Clicking on this button does not do anything because it's not supported at the moment.

**To Reproduce**
* Edit a markdwon document in NC Android client
* Select some text
* Click on "Link file"

Maybe we should just not render this button in the MenuBubble component when Text is displayed in the Android app. I don't know if Text's Vue components can check if they are rendered in the Android app.
`isMobile` mixin is off-topic here :grin:.

@juliushaertl @mejo- @azul @luka-nextcloud Any idea?

### PR DESCRIPTION
**Pull request by eneiluj**
closes #1975
This uses the initial state to determine if we are using direct edition.

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Great, thanks for taking care :+1:

**Comment by juliushaertl** [comment]
> Looks good codewise. I'm unable to test this easily.

Just in case needed for the future, there are API examples expandable in the description of https://github.com/nextcloud/server/pull/17625, but let me open an issue to move that to the documentation actually.

**Comment by juliushaertl** [comment]
Filed https://github.com/nextcloud/.github/issues/28 to improve the rebase/compile automation as long as we have bundles committed.

**Comment by eneiluj** [comment]
> Filed [nextcloud/.github#28](https://github.com/nextcloud/.github/issues/28) to improve the rebase/compile automation as long as we have bundles committed.

Nice to think we'll be able to avoid those long rebase with compiled assets :grin:.

**Pull request merged**
