### PR TITLE
fix: reconnect - reload main container

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

Introduce `hasEditor` as reactive data to dynamically reload the MainContainer.

`$editor` is not reactive.
Once the `MainContainer` was rendered it stayed - even when `$editor` was reset during reconnection.
The child components of `MainContainer` would still use the old `$editor` value.

* Fixes https://github.com/nextcloud/text/issues/3374.

This Pull request includes some refactoring and cleanup commits before and after the actual change.

Tests are not included as i could not think of a way to trigger the connection to expire.

### CODE REVIEW

**Comment by max-nextcloud** [comment]
/backport [a6913ea](https://github.com/nextcloud/text/pull/3627/commits/a6913ea2220aebec87875db68bac1a479c20964d) to stable25

**Review by juliushaertl — APPROVED** [review]
Great. Also good idea to pull out the moment updating.

**Comment by juliushaertl** [comment]
For a cypress test we could probably intercept the create session request, store the session id and token and then manually issue a close session request in the test.

**Comment by mejo-** [comment]
/backport 434f6e54577f4f15437bfb4b6ea5f16b0ec6af87,9b98212757b4af01534b73101eaba1c607bb1840,b7ec01b51fb9226086cde978ce35728aca022923,7360d1c8db69bab8c9ae64f104ec904249a0227d to stable25

**Pull request merged**
