### PR TITLE
[stable25] update tiptap

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

* Superseeds #3752 

Renovate keeps stepping on my toes when pushing to the original branch.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by max-nextcloud** [comment]
Funny... 3 cypress tests failing all somewhat related to opening links.

**Comment by blizzz** [comment]
conflicts

**Comment by juliushaertl** [comment]
Closing as discussed

**Pull request closed without merging**
