### PR TITLE
feat: switch to native browser tooltips

### PR DESCRIPTION
**Pull request by luka-nextcloud**
### 📝 Summary

* Resolves: #4321

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by max-nextcloud — CHANGES_REQUESTED** [review]
Code looks good at first sight but I noticed some problems when trying it out:
* Session List "Active People" is not shown anymore
* Emoji Picker menubar entry has no tooltip and funny color on dark background
* edit guest user name also has color issues on dark background.

I'm not sure if the funny colors are related or not. Will try with current master and provide screen shots.

**Comment by max-nextcloud** [comment]
### Missing title in session list
|Before: | Now: |
|---|---|
|Bildschirmfoto vom 2023-12-29 22-00-00| grafik |

Current Markup (notice `data-original-title`):
Bildschirmfoto vom 2023-12-29 22-00-46

### Funny color, no tooltip in emoji picker

grafik


### Funny colors in guest name - tooltip is fine
Bildschirmfoto vom 2023-12-29 21-57-30

**Comment by max-nextcloud** [comment]
Funny color in guest name entry also exists on stable28. So not caused by this.

**Comment by max-nextcloud** [comment]
@luka-nextcloud did you test the image insertion, active people and link picker?
They still don't show for me.
I checked out the branch, booted the nextcloud-docker-dev for server master, compiled the js and checked there.

**Comment by luka-nextcloud** [comment]
@max-nextcloud I have just checked again. It works well:
image
image
image

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
