### PR TITLE
Fix direct editing loading of txt files

### PR DESCRIPTION
**Pull request by juliushaertl**
### 📝 Summary

Fix loading txt files through direct editing

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/master/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
@max-nextcloud those were the changes from our earlier debugging session. Will add a cypress test later for this as well.

**Comment by juliushaertl** [comment]
I also figured out why the session id is being regenerated. It seems that the user id is now written to the session (which was not before 25) due to the fact that we change into the user scope. First attempt to properly address this is in https://github.com/nextcloud/server/pull/35360

**Review by max-nextcloud — APPROVED** [review]
Looks good. Minimal change, hopefully easy to backport to 25.

**Comment by max-nextcloud** [comment]
/backport e5f773bc895c1ee04ba8d42505c562e6efc4dea3, e5f773bc895c1ee04ba8d42505c562e6efc4dea3 to stable25

**Comment by max-nextcloud** [comment]
/backport e5f773bc895c1ee04ba8d42505c562e6efc4dea3, ca98523 to stable25

**Pull request merged**
