### PR TITLE
Trigger event on content change in syncservice

### PR DESCRIPTION
**Pull request by vinicius73**
* Resolves: #2462 
* Target version: master 

### Summary

Fires 4 events from `SyncService`

- `sync-service:idle`
- `sync-service:save`
- `sync-service:error`
- `sync-service:sync`

#### Prevention of Memory Leak

All `SyncService` event handlers are storage in arrays, and never removed from these arrays.
Although the `SyncService` whore removed from Vue component context, we had a circular reference here.
This is a very common scenario for Memory Leak in JavaScript.

Now using [`mitt`](https://github.com/developit/mitt) library is possible to use `.off` to remove an event handler.

To do it, I've change part of event contracts (error event) and I've split the event handlers in component methods.

There are more potential problems to solve, but we can do it later.

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Much cleaner 👍

**Comment by max-nextcloud** [comment]
Not sure if we really want to backport this - but since it prevents memory leaks and cleans things up seems like a good idea.

**Comment by mejo-** [comment]
Manual backported to stable24 in #2679

**Pull request merged**
