### PR TITLE
TaskItem: Don't allow toggling while editor is readonly

### PR DESCRIPTION
**Pull request by marcelklehr**
* Resolves: #1525
* Target version: master 

### Summary
TaskItem: Don't allow toggling while editor is readonly

My first text PR :v:

### CODE REVIEW

**Comment by juliushaertl** [comment]
Maybe the input could also be set to disabled in the renderHTML function?

**Comment by marcelklehr** [comment]
I wanted to do that, but I think we don't get the editor object passed in the renderHTML function to know whether we're readonly, do we?

**Comment by juliushaertl** [comment]
I think it should be available in the current object scope as `this.editor`, but not 100% sure.

**Comment by marcelklehr** [comment]
image

**Comment by mejo-** [comment]
> I wanted to do that, but I think we don't get the editor object passed in the renderHTML function to know whether we're readonly, do we?

If I didn't oversee anything, `this.editor` should be available in the scope of the Tiptap Node/Extension and so it should be in `renderHTML()`. So you should be able to use `this.editor.options.editable` there, no?

**Comment by marcelklehr** [comment]
Debugger says no. :D

**Review by mejo- — APPROVED** [review]
So in the end your approach is probably the best @marcelklehr.

I quickly tried the approach to implement a `isReadonly` flag in storage of the extension. While this works well, setting the checkbox to disabled in `renderHTML()` brings other problems and doesn't work as expected since `handleClick()` alters the `checked` attribute without respecting the `disabled` attribute anyway. So we would have to change the logic of `handleClick()`, which is probably not worth the effort.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
