### PR TITLE
fix: handle non markdown files in conflicts

### LINKED ISSUE #4205: .Txt Content deleted after restoring older Version an reopeninge with "Text"
**Describe the bug**
Lines in .txt Document dissapear 

**To Reproduce**
1. create text Document test.txt with 3 Lines:
"Line1"
"Blank line with "enter key""
"Line2"
Upload via drag and drop

2. Open with Text, add two lines
"Blank Linke with enter key"
"Line3"
Click Save or autosave ... close Document

3. Go to File Details - > Version
Curren Version and Inital Version are available
Restore Inital Version

4. Open File again with text.
Verison with 3 Lines is displayed, click "use saved Version" (Die gespeicherte Version verwenden). I'M using german UI.
After Click "Line3" and also "Line2" are removed.
only "Line1" is keept.

So Content from Initial Version is removed.

**Expected behavior**
Original Content with "Line1" and "Line2" is displayed

**Client details:**
 - OS: Win10
 - Browser: tested on Firefox and Edge (113)

<details>
<summary>Server details</summary>

**Text app version:**  3.7.2

**Operating system:**
Ubuntu 22.04

**Web server:**
Apache

**Database:**
Art: sqlite3

**PHP version:**
Version: 8.1.2

**Nextcloud version:** (see Nextcloud admin page)
26.0.1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:



</details>

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

Do not parse non markdown files when resetting the content.
Also add `CodeBlock` extension in Reader so it renders the server version.

Fixes #4205.

### 🚧 TODO

- [x] fix background of conflict view
- [x] tests

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Code looks good, trusting in cypress for testing

**Comment by max-nextcloud** [comment]
compile failures look like they might be related to the path setup on the runners. However it looked like this was a default github runner - so i don't quite understand what's going on here.

**Comment by mejo-** [comment]
> compile failures look like they might be related to the path setup on the runners. However it looked like this was a default github runner - so i don't quite understand what's going on here.

Yeah. To be honest for me the workaround is to just restart them until the job is picked up by a not self-hosted runner :see_no_evil:

**Comment by mejo-** [comment]
But the cypress failures look related to the PR, no? https://github.com/nextcloud/text/actions/runs/5214578471/jobs/9411036184?pr=4220#step:7:129

**Comment by mejo-** [comment]
/backport cc601a78b7bc224fe84088f8e377c2e8599821cd,8f5ca56d6beb2234746724e54d9c133b66736293,6a330e4a0c91b0274f53da2dac2d4825a9af1834,36f21e6ee2e2c338cb4e1a97218e16752f72954c to stable27

**Comment by mejo-** [comment]
/backport cc601a78b7bc224fe84088f8e377c2e8599821cd,8f5ca56d6beb2234746724e54d9c133b66736293,6a330e4a0c91b0274f53da2dac2d4825a9af1834,36f21e6ee2e2c338cb4e1a97218e16752f72954c to stable26

**Pull request merged**
