### PR TITLE
Conflict fixes

### PR DESCRIPTION
**Pull request by juliushaertl**
Couple of fixes around conflict handling and file save, split into individual commits for easier review:

- test: Add cypress tests for resolving conflicts
- fix: store actually used mtime
- fix: Properly restart sync after conflict resolution
- fix: Avoid writing file content if it has not changed
- fix: Fix styling of collision dialog and move it out of the editor
- fix: Do not disconnect during conflict to be able to catch up on a resolution

There is still some work left that probably involves design work to come up with better handling of the conflict display on mobile devices, but that is left out for now to have a more easily back portable change.

### 📝 Summary

* Resolves: #3961 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Screenshot 2023-03-22 at 18 44 30 | Screenshot 2023-03-22 at 18 44 09

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Will check the cypress test tomorrow, seems we should await the sync request after pushing the state as it passed before my squashing push.

**Review by mejo- — APPROVED** [review]
Nice, thanks for tackling this! Code looks good to me :ok_hand:

**Pull request merged**
