### PR TITLE
[stable27] preserve websocket provider queue during reconnects

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

* Backports #5126

### CODE REVIEW

**Comment by max-nextcloud** [comment]
We will need to investigate the sync spec failure in cypress. That might be related.

**Comment by juliushaertl** [comment]
I know one is also sometimes failing on other branches, but would be good to check, yes :)

**Comment by max-nextcloud** [comment]
> I know one is also sometimes failing on other branches, but would be good to check, yes :)

grafik
Looks like it's been failing quite consistently on `stable27` for a while now.

**Comment by max-nextcloud** [comment]
The failures look exactly the same as before. Opened #5154 to investigate further. Let's move on with this.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
@max-nextcloud Can you check the backport to 26?

**Pull request merged**
