### PR TITLE
Add paste event handler to allow pasting markdown

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes https://github.com/nextcloud/text/issues/16

Marking as draft as this still needs a bit of testing if this is feasible for common use cases of pasting random text

### CODE REVIEW

**Comment by juliushaertl** [comment]
While I have the use case very often, I'd still be curious if anyone could think of scenarios where just always parsing pasted text as markdown could be unexpected to users. Any objections @nextcloud/office ?

**Comment by mejo-** [comment]
Nice, I would love to be able to paste markdown and get it formatted direclty!

This should also fix #55.

**Comment by susnux** [comment]
> This should also fix #55.

No that one is about typing not pasting, but this would fix #938

**Comment by max-nextcloud** [comment]
> I'd still be curious if anyone could think of scenarios where just always parsing pasted text as markdown could be unexpected to users.

When pasting markdown into a codeblock i would expect it to show up as source code not interpreted as markup.

**Comment by marcelklehr** [comment]
Maybe this would be better as a context menu option similar to how Word processors have different options on how to paste

**Comment by susnux** [comment]
Or to follow common practice:

Use this for all normal paste and add a handler for `ctrl + shift + v` to paste without formatting.

**Comment by juliushaertl** [comment]
Changed the approach a bit by using `clipboardTextParser` and skipping the markdown parsing when `Ctrl+Shift+V` is used.

**Comment by juliushaertl** [comment]
🏓 For review ;)

**Review by susnux — APPROVED** [review]

**Pull request merged**
