### PR TITLE
Temporary editor colors during editing sessions

### PR DESCRIPTION
**Pull request by juliushaertl**
First attempt towards implementing https://github.com/nextcloud/text/issues/91 

For now the author annotation is only available during editing sessions

image

- [x] Make sure that color contrast ratio for text works properly
- [x] Check if we can indicate the author colors better in the avatar list
- [x] Since we currently use the session id as an identifier author annotation might also be lost as soon as one leaves the document and the session is cleaned up
	- [x] should at least persist the session metadata as long as the document is open
	- ~otherwise we might be able to persist decorations as marks in the document which would be also useful for persisting them later on~

## Follow up
- [ ] decorations are always rendered into the dom which might have a performance impact on larger files -> check if there might be a way to only render decorations if actually needed

cc @jancborchardt for design feedback :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Aaawesome! :) So if we use the same colors as for the avatars, the contrast should work, as @skjnldsv made sure that contrast is enough. :)

Even if it's only enough for WCAG A or AA level that is fine though, since it can just be turned off and full text contrast is there.

----

About the indication of the color in the avatar list, you are referring to the issue that when people have avatars, the placeholder color is not visible, right?

I'd say a fix here is to give the avatar a 2px border of the author color. That would work both in the list of avatars-only as well as in the menu including the names.

**Comment by jancborchardt** [comment]
Alternative for the highlight color as discussed: Reduce opacity of the author color so we can keep the text black, would make it more readable. And then the highlight color looks more like a text marker pen. :)

**Comment by juliushaertl** [comment]
Ready for review and testing

**Review by ChristophWurst — APPROVED** [review]
Code looks good as far as I can judge :+1:

**Pull request merged**
