### PR TITLE
Do not try to get a displayname for guests

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by max-nextcloud** [comment]
cypress tests are still failing but now they are exposing a different issue. Somehow there's no menubar and the editor is in a funny state when loaded from the share token. I have not been able to reproduce this outside of cypress yet though.

**Comment by max-nextcloud** [comment]
Looks like the editable share doesn't do what i thought it does. May have to turn this into two requests or so.

**Review by max-nextcloud — APPROVED** [review]
Fixes the issue i ran into when trying to fix the cypress tests.

**Comment by juliushaertl** [comment]
Awesome, thanks a lot.

**Pull request merged**
