### PR TITLE
change tab-size to 4

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/text/issues/1591

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Hm... not sure why `Node / node (pull_request) ` is failing... any idea?

**Comment by szaimen** [comment]
> Lets see if compile bot does work this time :)

Looks like it 😆

Thanks for compiling and pushing! :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
