### PR TITLE
Append a newline after inserted image

### PR DESCRIPTION
**Pull request by mejo-**
When uploading/inserting multiple images at once, an empty line will be
in between the images. This makes it easier to place content in between
the images.

Fixes: #2784

Signed-off-by: Jonas <jonas@freesources.org>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
looks good to me.

**Comment by mejo-** [comment]
Manual backport to stable24: https://github.com/nextcloud/text/pull/2864

**Pull request merged**
