### PR TITLE
Add text/asciidoc mimetype

### PR DESCRIPTION
**Pull request by bjornfor**
### 📝 Summary

This allows editing AsciiDoc files, as plain text.

This change depends on
https://github.com/nextcloud/server/commit/582f07c8fc47d4a775f05fbaad32269753d944f0
("Add text/asciidoc mimetype").

Signed-off-by: Bjørn Forsman <bjorn.forsman@gmail.com>

~Disclaimer: this is a trivial change, but I haven't tested (I don't know how).
I based this on
https://github.com/nextcloud/text/issues/394#issuecomment-1188860327~ It has a test now.

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/master/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by max-nextcloud** [comment]
Hi @bjornfor,

Thanks a lot! That seems like a useful addition. Code also looks good.

I added a test for two mimetypes we already support here: https://github.com/nextcloud/text/pull/3540.
Would that work as a basis for adding tests for you?

I'd be curious to see if you can add a test with this. If you get stuck or miss some documentation please let me know so we can make this work more smoothly.

**Comment by bjornfor** [comment]
Hi @max-nextcloud, thanks, I can probably make a copy of the plain text test, without fully understanding it :smile:

**Comment by bjornfor** [comment]
@max-nextcloud: I rebased and added a test, but I think `cy.getContent().find('pre').should('exist')` part isn't quite right.

So `find()` looks for HTML tags (right?), and in the "empty.md" test you added I think the test just checks that the overall HTML page contains a `pre` element. In the "markdown" test, the code checks for a `h2` tag that comes from converting markdown to HTML. But for this AsciiDoc code, we don't get any special markup (it's treated as plain text), but we would perhaps like to check that the text *content* got rendered?

I guess I'd like to say `cy.getContent().SOMETHING_HERE.should('contain', 'Hello world')`, but don't know what `SOMETHING_HERE` should be.

**Comment by bjornfor** [comment]
> I guess I'd like to say `cy.getContent().SOMETHING_HERE.should('contain', 'Hello world')`, but don't know what `SOMETHING_HERE` should be.

Does `cy.getContent().find('pre').should('contain', 'Hello world')` work?

**Comment by susnux** [comment]
The `getContent()` part restricts the following `find` to the editor content (whereas `get()` always searches the whole document).
So this is working as expected.

**Review by max-nextcloud — APPROVED** [review]
Hey @bjornfor 

Thanks for adding the test. Congratulations for figuring it out without understanding it.
:key: achievement unlocked :wink: 

> Does `cy.getContent().find('pre').should('contain', 'Hello world')` work?

Yes - that should do the trick. As @susnux explained `getContent` only looks at the content of the editor.
Feel free to add the hello world check - test also seems okay for me as is because it tests that text is loading the file.

Your last commit seems to lack a signoff. Other than that i think this is ready to go.

The failing `node` test is because the js still needs to be build here by commenting with `/compile`. It's a mess and we're working on fixing it. I can take care of that once you signed off the second commit.

**Comment by bjornfor** [comment]
@susnux @max-nextcloud: Thanks. I added `Signed-off-by:` and update the test with `cy.getContent().find('pre').should('contain', 'Hello world')`.

**Comment by max-nextcloud** [comment]
CI failure is not related.

**Comment by bjornfor** [comment]
@max-nextcloud: Thanks!

**Pull request merged**
