### PR TITLE
Replace MenuBubble with a menu bar entry for links

### LINKED ISSUE #1528: No way to remove formatting. Must delete text and retype.
**Describe the bug**
No way to remove formatting. Must delete text and retype. eg You accidentally backspace, and an entire paragraph becomes H1. You can put in a line break, but the paragraph remains as H1 FOR EVER. Need to delete entire paragraph. Or, cut, paste into external text editor, cut from there, and paste back into App. 

Needs Remove formatting button. 

**Client details:**
Firefox Linux Latest

### LINKED ISSUE #2392: Move away from menu bubble
Adding links to files and URLs through the menu bubble has shown all kind of issues in regards to mobile usage (like the native menu of android/iOS conflicting with ours) and the discoverability of those features. As we talked about this in the design call we should probably move those elements to the menu bar, maybe grouped as a "Link" option with a popover showing:

- Link to URL
- Link to file

Replaces https://github.com/nextcloud/text/issues/81

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #2162, and resolves #2392, and resolves #1528 (adds the missing functionality to remove link marks)
* Target version: master 
* Supersedes: #2457

### Summary
This replaces the popover MenuBubble used for inserting links with a menu entry in the menu bar.
This also allows to add links also to directories, previously only files were allowed as link targets.

Added cypress tests as well. Testing inserting links to files, to directories,
and also inserting links while nothing is selected to test if the correct file name is used. 

Some the menu order is slightly changed to prevent the link menu to get hidden, like for the callouts
`Actions` must not get hidden in the submenu (nesting does not work for the menu).

Another feature introduced with this change is the ability to insert links to files and automatically use
the filename as the link text.

### CODE REVIEW

**Comment by susnux** [comment]
Rebased onto current master

**Comment by vinicius73** [comment]
I'm trying to test it locally, but I'm having errors to build @susnux 

image

**Comment by susnux** [comment]
> I'm trying to test it locally, but I'm having errors to build @susnux

That is not a issue of this PR, but a problem within the current `package.json`, https://github.com/nextcloud/text/commit/5b5d6cf56f990bf136f414904d21e0128549e963 added `"stylelint-config-recommended-scss": "^6.0.0"` but this conflicts with `"@nextcloud/stylelint-config"`.
So this leads to a broken state of the `node_modules`, you can fix this by set `"stylelint-config-recommended-scss": "^5.0.2"` in the `package.json` and rerun `npm install`.

**Comment by vinicius73** [comment]
I'm not having this issue in master @susnux, but I will check, thanks.

**Comment by vinicius73** [comment]
Looks like a "npm version problem"
We recommend the usage of Node v14 + NPM v7
But, NPM v7 is not shipped with Node v14...

**Comment by susnux** [comment]
Ok this is weird: This issue is related to the `ActionInput` component used in the PR, as it uses `@nextcloud/calendar-js`.
The problem is `@nextcloud/calendar-js` has a `peerDependency` on `ical.js` but `@nextcloud/vue` does not include that dependency.

So I would say `@nextcloud/vue` needs to be fixed.

But the weird thing is: If I fix this version issue (`stylelint-config-recommended-scss`), remove the packe-lock and run `npm install` it installes `ical.js`.

> Looks like a "npm version problem" We recommend the usage of Node v14 + NPM v7 But, NPM v7 is not shipped with Node v14...

Normally I use node16 + npm8 (as node14 is EOL and my distribution does not ship it anymore), but for this I tried also node14+npm7: Result is the same there is a package version mismatch (same error as above).

**Comment by skjnldsv** [comment]
> as node14 is EOL

Node 14 is still maintained as last LTS for 10 more months
https://endoflife.date/nodejs

**Comment by susnux** [comment]
@vinicius73 
> /rebase

Rebased manually there were some conflicts with the cypress part.

**Comment by susnux** [comment]
I moved the PR to https://github.com/nextcloud/text/pull/2665, so the assets can be compiled (and the node CI test succeeds), as suggested here https://github.com/nextcloud/text/pull/2628#issuecomment-1173160648

**Pull request closed without merging**
