### PR TITLE
Add new text file action label

### PR DESCRIPTION
**Pull request by Pytal**
### 📝 Summary

- For https://github.com/nextcloud/server/pull/37929

API changes require the above PR to be merged first

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Server PR merged, restarted cypress tests. Static analysis is expected to fail until the next ocp meta package update.

**Comment by Pytal** [comment]
Drafting until next https://github.com/nextcloud-deps/ocp update

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Manually bumped ocp and it is passing https://github.com/nextcloud/text/actions/runs/4827564521/jobs/8600422284

**Pull request merged**
