### PR TITLE
Fix bullet list input role for CJK input

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #2749
* Target version: master 

### Summary
When using IME for CJK character input it is called after the composing
is finished, at this point there might be more than one character.

#### Example
Before entering the same work (`sakura`) as Japanese Kanji and Hiragana, Kanji is one symbol so it worked, Hiragana are three syllables symbols so it does not:
Input using IME does not work

After this patch using IME works as expected:
Input using IME is correctly formatted

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
Good catch, minimal fix to the point -- thanks a lot!
I wonder if there would be an easy way to test this. But i don't think we're testing input rules yet.

**Review by juliushaertl — APPROVED** [review]

**Comment by susnux** [comment]
> I wonder if there would be an easy way to test this. But i don't think we're testing input rules yet.

I wanted to add a cypress test, but I did not find a way to test IME input

**Comment by susnux** [comment]
I think this should also be backported to stable 24

**Pull request merged**
