### PR TITLE
ci: github action for composer

### PR DESCRIPTION
**Pull request by max-nextcloud**
Validate composer and ensure composer install actually works.

* Target version: master 

This is meant to replace the drone compatibility check

### CODE REVIEW

**Comment by eneiluj** [comment]
Can we implement all drone checks in a GitHub action? That would be awesome.

**Comment by max-nextcloud** [comment]
> Can we implement all drone checks in a GitHub action? That would be awesome.
I think this is the only missing part. We already have php unit tests run by github actions.

**Comment by max-nextcloud** [comment]
Removed the drone config... but i think it's just listening to what's in master currently. On the other hand this means that if we merge this other branches will also stop running drone.

**Comment by mejo-** [comment]
Probably this is obsolete now that we have #1679 in, right?

**Comment by max-nextcloud** [comment]
> Probably this is obsolete now that we have #1679 in, right?

I don't know. Does `composer validate` do anything that the php setup routine does not? I'll look it up.

**Comment by max-nextcloud** [comment]
Looks like composer validate performs some checks - but some of them we don't care about such as checking if it could be published. Also we still ignore warnings in this test. Not sure if it would catch anything that our other tests don't catch. So i'll just close this and we can add it once we notice we would have needed it.

**Pull request closed without merging**
