### PR TITLE
Comply to new addScript API

### PR DESCRIPTION
**Pull request by mejo-**
Required by https://github.com/nextcloud/server/pull/30015

Signed-off-by: Jonas Meurer <jonas@freesources.org>

* Target version: master

### CODE REVIEW

**Review by eneiluj — APPROVED** [review]
Nice and clean.

**Comment by mejo-** [comment]
Apparently that doesn't work outside the Files app. In Collectives for example, the handlers are no longer registered due to a race condition. From JS console:

```
Viewer app is not installed viewer.js:41
    <anonym> viewer.js:41
    <anonym> text-viewer.js:2791
    <anonym> text-viewer.js:2793
OCA.Viewer initialized
OCA.Viewer.availableHandlers.map(h => h.id)
Array(3) [ "images", "videos", "audios" ]
```

So for some reason, the Viewer app is only initialized *after* the Text app when loading Collectives :thinking:

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
@mejo- Maybe related to https://github.com/nextcloud/viewer/pull/1081/files#diff-a14aae69340720190ddf327b54675eacd97116b45f5b57f583ddb52829a3f152R41 where viewer seems to depend on files?

**Comment by mejo-** [comment]
> @mejo- Maybe related to https://github.com/nextcloud/viewer/pull/1081/files#diff-a14aae69340720190ddf327b54675eacd97116b45f5b57f583ddb52829a3f152R41 where viewer seems to depend on files?

Indeed, that's the change that breaks initializing Viewer in Collectives. After removing the `Files` dependency from `Util::addScript()`, it works again.

Mh, so apparently our trick to load the Text app through the Viewer handler in Collectives finally breaks. Maybe @azul can have a closer look here :grimacing:

**Comment by skjnldsv** [comment]
> So for some reason, the Viewer app is only initialized _after_ the Text app when loading Collectives thinking

Can you debug the scripts list and order?
https://github.com/nextcloud/server/blob/791d57051ad4d5fd6f24a0e8c200ca1fc8555c3e/lib/public/Util.php#L243
Getting the `self::$scripts` raw array before it gets flattened?

**Comment by skjnldsv** [comment]
> Indeed, that's the change that breaks initializing Viewer in Collectives. After removing the `Files` dependency from `Util::addScript()`, it works again.

Maybe there is some corner case I didn't considered when doing this.
```

**Comment by juliushaertl** [comment]
@mejo- Good to go or do you want to investigate first further in regards to the collectives integration before we merge?

**Comment by mejo-** [comment]
> Maybe there is some corner case I didn't considered when doing this?

The problem is that the `files` dependency of `viewer` moves `viewer/js/viewer-main` to the `last` element of `files`, while the `viewer` dependendy on `text` moves `text/js/text-viewer` to the `last` element of `viewer`. Viewer is before files but `viewer` no longer contains `viewer/js/viewer-main`, so loading `text/js/text-viewer` from `last` fails.

`self::$scripts` from https://github.com/nextcloud/server/blob/791d57051ad4d5fd6f24a0e8c200ca1fc8555c3e/lib/public/Util.php#L243 when loading the Collectives app:

```json
{
  "accessibility": {
    "first": [
      "accessibility/l10n/en",
      "accessibility/js/accessibilityoca"
    ]
  },
  "files_sharing": {
    "first": [
      "files_sharing/l10n/en",
      "files_sharing/js/dist/main"
    ]
  },
  "text": {
    "first": [
      "text/l10n/en"
    ]
  },
  "viewer": {
    "first": [
      "viewer/l10n/en"
    ],
    "last": [
      "text/js/text-viewer"
    ]
  },
  "files": {
    "first": [],
    "last": [
      "viewer/js/viewer-main"
    ]
  },
  "theming": {
    "first": [
      "theming/l10n/en",
      "theming/js/theming"
    ]
  },
  "user_status": {
    "first": [
      "user_status/l10n/en",
      "user_status/js/user-status-menu"
    ]
  },
  "core": {
    "first": [],
    "last": [
      "core/js/dist/unified-search"
    ]
  }
}
```

After removing `files` dependency from `viewer` (in https://github.com/nextcloud/viewer/pull/1081/files#diff-a14aae69340720190ddf327b54675eacd97116b45f5b57f583ddb52829a3f152R41):

```json
{
  "accessibility": {
    "first": [
      "accessibility/l10n/en",
      "accessibility/js/accessibilityoca"
    ]
  },
  "files_sharing": {
    "first": [
      "files_sharing/l10n/en",
      "files_sharing/js/dist/main"
    ]
  },
  "text": {
    "first": [
      "text/l10n/en"
    ]
  },
  "viewer": {
    "first": [
      "viewer/l10n/en",
      "viewer/js/viewer-main"
    ],
    "last": [
      "text/js/text-viewer"
    ]
  },
  "theming": {
    "first": [
      "theming/l10n/en",
      "theming/js/theming"
    ]
  },
  "user_status": {
    "first": [
      "user_status/l10n/en",
      "user_status/js/user-status-menu"
    ]
  },
  "core": {
    "first": [],
    "last": [
      "core/js/dist/unified-search"
    ]
  }
}
```

**Comment by mejo-** [comment]
So I guess that we need a more complex dependency management logic in `Util::addScript()` and `Util::getScripts()` to sort scripts by dependencies. Anyway, out of scope of this PR. I opened https://github.com/nextcloud/server/issues/30278 to track and discuss this issue.

**Pull request merged**
