### PR TITLE
feat: update render markdown for tables

### PR DESCRIPTION
**Pull request by luka-nextcloud**
### 📝 Summary

* Resolves: #3516 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Cypress failure looks unrelated, but can you check the jest tests again @luka-nextcloud ?

**Review by max-nextcloud — APPROVED** [review]

**Comment by max-nextcloud** [comment]
funny that the node check is passing without a compile.

**Comment by juliushaertl** [comment]
@luka-nextcloud Can you take care of the manual backport please?

**Pull request merged**
