### PR TITLE
Fix cypress scripts for local run + Add documentation

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/text/pull/2457#issuecomment-1143764123 (comment)
* Target version: master 

### Summary

Fix the scripts for local cypress runs,
they need to be run within the `npm run` environment,
as the nextcloud webpack config requires the `npm_package_name`
variable to be set.

Also a up-to-date nextcloud instance is required for testing
text at the current git head, so updated the dockerfile
and docker-compose files to create a nextcloud image from current git head.
(To get it work I modified the docker part to create a similar image as the one used by the github CI)

Additionally updated the tests to use cypress 10.x and
added missing documentation on how to run the cypress tests.

### CODE REVIEW

**Comment by vinicius73** [comment]
Thanks a lot for this @susnux 
I've adjusted some parts of your PR 

- The speed of build test image build (using [`--depth`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt))
- Apply [ShellCheck](https://www.shellcheck.net/) in `runLocal.sh`
- Fix apps folder permission

**Review by vinicius73 — APPROVED** [review]

**Comment by susnux** [comment]
> Thanks a lot for this @susnux I've adjusted some parts of your PR
> 
>     * The speed of build test image build (using [`--depth`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt))
> 
>     * Apply [ShellCheck](https://www.shellcheck.net/) in `runLocal.sh`
> 
>     * Fix apps folder permission

Looks good, it's only important to mount into custom apps, because docker will otherwise remove your current directory (or more precisely the nextcloud entry point)

**Review by juliushaertl — APPROVED** [review]
Very nice, thanks for documenting those parts and the improvements :)

**Comment by susnux** [comment]
> Thanks a lot for this @susnux I've adjusted some parts of your PR

Have you tried it? For me it works the first time but then stops working

**Comment by vinicius73** [comment]
Very strange @susnux 
Works every time for me, I've spent a long time adjusting it :/

**Comment by susnux** [comment]
Not sure why but the `custom_apps` directory gets created with `root` as the owner, see #2515 which works for me by forcefully `chown` the directory.
I tried to debug it but not sure if it is caused by docker while bind-mount the directory or the nexcloud entrypoint script.

**Pull request merged**
