### PR TITLE
Fix/2267 table tweaks

### PR DESCRIPTION
**Pull request by max-nextcloud**
* See: #2267 
* Target version: master 

### Summary

Fixes the two main ui issues:
* make sure text after the table starts on a new line
* hide actions in read only view

### CODE REVIEW

**Comment by juliushaertl** [comment]
@max-nextcloud Feel free to adjust the label to "to review" once ready :)

**Comment by max-nextcloud** [comment]
@juliushaertl Good point... let's get this in as it affects the ui and would be nice to have for screencasts etc. The other remaining todo items in the issue are less important for now.

**Pull request merged**
