### PR TITLE
Fix copy and paste of user mentions

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #3110

Signed-off-by: Jonas <jonas@freesources.org>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Review by vinicius73 — APPROVED** [review]

**Comment by vinicius73** [comment]
@mejo- check if it solves this CI https://github.com/nextcloud/text/pull/3266

**Comment by max-nextcloud** [comment]
The tests are failing because markdownit will still produce html output with `data-type="user"`. It takes the type argument from the first path element inside the `mention://user/...` url.

I named the tiptap extension `user` so it's consistent with the that.

**Comment by mejo-** [comment]
@max-nextcloud unfortunately your approach leads to other undesired sideeffects. I went with a different solution now. Also pushed some further minor improvements to user mentions along the way.

@vinicius73 @max-nextcloud @juliushaertl @luka-nextcloud would be nice if you could do a second review :grin:

**Review by max-nextcloud — APPROVED** [review]
Looks good to me.
Didn't test though.

**Comment by mejo-** [comment]
/backport ee9c9417bfff65b1b5b82dc2ddf384f664dddbba,492e14ec3e78bd4565c2b9d9f23cef82120767bc,5aad842b0c1677d8ff28291a3b57135ed4d4ed1c,5bca96084e39fbd536b9ddfdee63087d0de589d7 to stable25

**Comment by max-nextcloud** [comment]
@mejo- I tried it and it worked. Only the tab completion did not work - it focussed the sidebar / the close modal button. I think it might be missing a focustrap if it should work to autocomplete the mention.

**Comment by mejo-** [comment]
> Only the tab completion did not work - it focussed the sidebar / the close modal button. I think it might be missing a focustrap if it should work to autocomplete the mention.

Interesting. For me, tab completion works now - both for emojis and for user mentions. I tested on latest master (server and text) :thinking:

**Comment by max-nextcloud** [comment]
> Interesting. For me, tab completion works now - both for emojis and for user mentions. I tested on latest master (server and text) thinking

Interesting - in both cases tab is moving to the modal controls for me - both in firefox and chromium. I updated server, viewer and circles to the current state of master.

**Comment by max-nextcloud** [comment]
> Interesting. For me, tab completion works now - both for emojis and for user mentions. I tested on latest master (server and text) thinking

Interesting - in both cases tab is moving to the modal controls for me - both in firefox and chromium. I updated server, viewer and circles to the current state of master.

**Pull request merged**
