### PR TITLE
feat: hide share and close buttons on direct editing for desktop

### PR DESCRIPTION
**Pull request by luka-nextcloud**
### 📝 Summary

* Resolves: #3819 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image
 | 
image

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
/backport 1764ea49599199c333482c019ef3a39af6d4efdc to stable27

**Comment by juliushaertl** [comment]
@luka-nextcloud Please have a look

**Comment by luka-nextcloud** [comment]
https://github.com/nextcloud/text/pull/5099

**Pull request merged**
