### PR TITLE
Do not remove escaping from brackets

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #2703
* Target version: master 

### Summary
See #2703 for full description

Removed the erroneous replacement of escaped brackets with plain brackets as this breaks valid markdown.
Added a test case for this.

Added markdownit and tiptap extensions to tag special characters (characters which might have a special meaning for markdown) that are not parsed by markdownit, e.g. because they are extended markdown syntax. The tags are only stripped if the user edits it that part of the file.
This way we can ensure they do not get escaped by `prosemirror-markdown`.

### CODE REVIEW

**Comment by susnux** [comment]
Do not merge, still some work to do (WIP).... implementing some more markdown fixes.

**Comment by susnux** [comment]
Added test cases, all tests pass I think this can be reviewed :smiley:

**Comment by vinicius73** [comment]
This PR fix one or two problems @susnux ?

**Comment by susnux** [comment]
> This PR fix one or two problems @susnux ?

Well actually three problems

1. I fixed https://github.com/nextcloud/text/issues/2703 which is quite simple but solves the problem: https://github.com/nextcloud/text/pull/2704/files#diff-6591e0135928d4bf8e3856079a58f0453ddfd4a62a71d923c30cbd2913973cb2
2. That fixes that problem but reintroduces https://github.com/nextcloud/text/issues/325 so thats why I added the `keep syntax` extensions, those extension simply add marks for parts of the original markdown file that would be escaped when serializing the editor and if present when serializing they will prevent escaping of that region. Those marks stay until the user manually edits that part.\
So as an benefit this also fixes parts of https://github.com/nextcloud/text/issues/593 and https://github.com/nextcloud/text/issues/2577

**Comment by susnux** [comment]
@vinicius73 if preferred I can split this PR into two, one for fixing the issue and one for switching the dependency to fix the other issue.

**Comment by susnux** [comment]
I decided to split the PR as the switch of the dependency was not really needed to fix this issue, but another.

So this in now only fixing the issues described in the comment above ( https://github.com/nextcloud/text/pull/2704#issuecomment-1184269724 ), for the other part see: #2720

**Comment by vinicius73** [comment]
Thanks for it @susnux

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
