### PR TITLE
fix: use OC.Files API to get file info

### PR DESCRIPTION
**Pull request by azul**
This api is also available in other apps while
the internal structures used in fetchFileInfo are not.

* Resolves: #920 
* Target version: master 

### Summary

The [old code in question](https://github.com/nextcloud/text/blob/stable19/src/helpers/files.js#L67) tried to use 
`OCA.Files.App.fileList` : 
```javascript
const files = OCA.Files.App.fileList.filesClient._client.parseMultiStatus(response.data)
```
This is not available when using text in the viewer inside another app such as spreed during a call.

### CODE REVIEW

**Comment by azul** [comment]
@juliushaertl this should be a quick review. :eyes: 

Could you please take a look so I can then adjust #879 to it?

**Comment by MorrisJobke** [comment]
🙄

**Pull request merged**
