### PR TITLE
Add syntax highlighting in code blocks

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #3618

Also only load core highlight JS package in EditorFactory.js (required for syntax highlighting in plaintext editing). This reduces the size for compiled editor.js by almost 1MB.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing
- [x] Documentation is not required

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
:tada: 

Wow! So little changes - so much impact!

**Comment by mejo-** [comment]
/backport f1a0fea97ed574e16cf39b06d69e9263405a5edf to stable26

**Comment by mejo-** [comment]
/backport f1a0fea97ed574e16cf39b06d69e9263405a5edf to stable27

**Pull request merged**
