### PR TITLE
⬆️ @nextcloud/vue v7

### PR DESCRIPTION
**Pull request by vinicius73**

### CODE REVIEW

**Review by eneiluj — COMMENTED** [review]
Seems all good.. Clicked around the interface and no issue found.

Tests are not passing locally though. In share.spec.js:
```
Timed out retrying after 4000ms: Expected to find element: #viewer[data-handler="text"], but never found it.
```
image

**Comment by max-nextcloud** [comment]
> Tests are not passing locally though. In share.spec.js:

Passed twice for me. I'll approve and we can investigate the failing test later.

**Pull request merged**
