### PR TITLE
l10n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

**Comment by max-nextcloud** [comment]
/backport 8179c14 52eca5e 7f3deac 9319da7 to stable24

**Comment by juliushaertl** [comment]
@rakekniven Small hint, if you use the rebase feature to update a branch, this will allow the backport bot to automatically open pull requests for the stable branches :)

https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#update-your-pull-request-branch-by-rebasing

**Comment by juliushaertl** [comment]
Referring to this PR, as I noticed you committed a merge with master, which is likely coming from pressing the Update branch button:

Screenshot 2022-08-02 at 21 11 02

Screenshot 2022-08-02 at 21 13 28

**Pull request merged**
