### PR TITLE
Fix pressing the enter key removes heading content

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #3150
* Target version: master 

### Summary
`div` is not an allowed child element of a `hX` tag, this leads to invalid behavior on firefox so we need to use the `span` tag as the NodeView content container.

Also using `tabindex=-1` on the NodeView will trigger weird behavior when clicking inside the heading and pressing the enter key. It will split the node but also copy the heading anchor link of the NodeView.

### CODE REVIEW

**Comment by juliushaertl** [comment]
I figured out that the `-webkit-user-modify` seems to cause quite some side-effects, so I pushed a fix to revert this change.

**Comment by juliushaertl** [comment]
Regarding cypress it seems that the way we clear the content editable is not very reliable in combination with the heading node view, so I moved the failing tests over to start with an empty file by default to avoid that. Something we should investigate separately in a follow up to maybe unify that logic or find a more stable way to clear the content.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
File as follow up issues:
- [ ] See if we need a different approach for https://github.com/nextcloud/text/pull/2712 or if we can live with that
- [ ] Unify cypress test setup to start with empty files
- [ ] Check if there is a better way to clear the content editable within cypress

**Review by max-nextcloud — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks a lot @susnux for the quick fix. Your contributions are highly appreciated. ❤️ 

On a separate note, we have a few public chat rooms on our Nextcloud instance, one also for text development, to stay in closer contact with community contributors and I thought it would also be cool to have you there. In case you are interested, just drop me a mail with your email address, then I can send you an invite.

**Pull request merged**
