### PR TITLE
Fix internal links in direct-edit sessions

### PR DESCRIPTION
**Pull request by Raudius**
### 📝 Summary

* Resolves: https://github.com/nextcloud/text/issues/1169
* Partially addresses: https://github.com/nextcloud/text/issues/1170

Internal links previously relied on OCA.Viewer to fetch the relative path of the document. In direct-edit sessions OCA.Viewer is not set. 

This PR adds a check for OCA.Viewer before handling internal links.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/master/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Cypress failures are unrelated. Will push a fix for a recent server change shortly.

**Comment by juliushaertl** [comment]
Fix in https://github.com/nextcloud/server/pull/35866

**Comment by max-nextcloud** [comment]
I tried to create a cypress test for this here: https://github.com/nextcloud/text/tree/test/direct-editing-with-link

But the test won't fail even with the current master. So i am obviously failing to understand somethign about the underlying problem. Could you take a look at the test and check what i am missing?

**Comment by mejo-** [comment]
@juliushaertl is this PR still ready to be merged? Since you approved it earlier, is there a reason not to merge it?

**Comment by juliushaertl** [comment]
Nothing blocking from my side, let's get this in

**Pull request merged**
