### PR TITLE
fix: Ensure to not persist user put into the session for direct editing

### LINKED ISSUE #3848: User session might be persisted
https://github.com/nextcloud/text/blob/main/lib/Controller/SessionController.php#L110 should get reset after controller method calls that make use of it as otherwise this may load to the current session getting updated with a different user.

I've seen this happening locally with:
- tab 1: Having a tab open with a text editor
- tab 2: Logout in a second tab
- tab 2: Login as a different user
- tab 2: Navigate to another page
- tab 2: See that you're logged in as the previous user

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #3848

### CODE REVIEW

**Review by marcelklehr — APPROVED** [review]
Makes sense!

**Comment by sascha-wi** [comment]
How do I know if this issue will also be fixed in v24?

**Comment by HumBelele** [comment]
> How do I know if this issue will also be fixed in v24? Or is v24 not affected at all by this?

NC 24 is out of active Support. So no further Updates for Version 24.

**Pull request merged**
