### PR TITLE
[stable22] upgrade: all of prosemirror

### PR DESCRIPTION
**Pull request by max-nextcloud**
There have been some fixes to Android behavior.

* Target version: stable22

### CODE REVIEW

**Comment by max-nextcloud** [comment]
For now i just created the branch for testing... but we might want to get this in anyway... What do you think @juliushaertl ?

**Comment by juliushaertl** [comment]
Yeah probably makes sense to regularly do that for the stable branches manually as dependabot would only bump patch releases.

**Comment by max-nextcloud** [comment]
@juliushaertl any idea what's up with the static analysis?

**Comment by juliushaertl** [comment]
Yes, seems there is a conflict between out composer lock file version and what the OCP package pulls in ... pushed an update in #2491

**Comment by max-nextcloud** [comment]
@juliushaertl just confirmed with @tobiasKaminsky that this fixes some of the Android issues in text. So we should definitely get this in.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated

**Pull request merged**
