### PR TITLE
Fix editable attachment

### PR DESCRIPTION
**Pull request by vinicius73**
### Summary

Any text inside the editor was editable, even if this content is not related from the source.

This PR fix it in `ImageView.vue`

### CODE REVIEW

**Comment by vinicius73** [comment]
Waiting for https://github.com/nextcloud/server/pull/34396 to fix CI

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
/backport 787077b1d2c1739a4d9fd081df68a52fb31079b8,4751007fcf1266007635aec715b12f5c7b90cab2 to stable25

**Pull request merged**
