### PR TITLE
fix(css): info callout box color to --color-info

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

Fallback to the hard coded value for our primary element default. `--color-info` was only introduced with Nextcloud 27.
* Resolves: #4161 

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- no tests as we do not test css styles (yet).
- Documentation is not required

### CODE REVIEW

**Comment by max-nextcloud** [comment]
/backport c564511d9459e5bbbd0685a768920e44ebba9506 to stable27

**Comment by max-nextcloud** [comment]
/backport c564511d9459e5bbbd0685a768920e44ebba9506 to stable26

**Comment by max-nextcloud** [comment]
/backport c564511d9459e5bbbd0685a768920e44ebba9506 to stable25

**Review by mejo- — APPROVED** [review]
Thanks a lot for tackling this!

**Pull request merged**
