### PR TITLE
[stable21] Use file.path to track more accurately EditorWrapper instances

### PR DESCRIPTION
**Pull request by eneiluj**
Backport of #2145

### CODE REVIEW

**Review by mejo- — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Review by max-nextcloud — DISMISSED** [review]
Blocking since this may have unintended consequences.

Say i edit a file and you rename it in the meantime... What should happen? I think it's a feature and not a bug, that the editing keeps working and i now edit the file with the new name.

**Pull request merged**
