### PR TITLE
[stable26] feat: Add Shift-Mod-C for copying the markdown source

### PR DESCRIPTION
**Pull request by mejo-**

### CODE REVIEW

**Comment by blizzz** [comment]
feature to 26? :eyes:

**Comment by blizzz** [comment]
moving to 26.0.1 as discussed

**Comment by nickvergessen** [comment]
Merge?

**Comment by juliushaertl** [comment]
Autoload checker unrelated, will update separately.

**Comment by juliushaertl** [comment]
Wrong click order but tested and approved 👍

**Pull request merged**
