### PR TITLE
[stable27] ci(cypress): Fix selectors for new file picker

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix CI after new file picker got merged

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
Thanks a lot for taking care of this.
:green_heart:

**Comment by juliushaertl** [comment]
Needs a forward port once the file picker is also merged on server master

**Pull request merged**
