### PR TITLE
[stable21] fix: rich workspaces overlap with new file dropdown

### PR DESCRIPTION
**Pull request by szaimen**
backport of #1574

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by juliushaertl — CHANGES_REQUESTED** [review]
- [ ] Needs testing if it still causes issues with IE11 as we still support that for 21

**Comment by blizzz** [comment]
what's the state here?

**Comment by szaimen** [comment]
It still needs testing with IE 🤷‍♂️

**Comment by blizzz** [comment]
scary

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
