### PR TITLE
Shrink heading anchor links to `1em`, fixes links in headings

### PR DESCRIPTION
**Pull request by mejo-**
In readonly mode, the heading anchor links spanned the whole width so far, overlaying potential links in headings.

Fixes: #3822

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

### CODE REVIEW

**Review by susnux — APPROVED** [review]
:+1:

**Comment by mejo-** [comment]
/backport fc802d0d73da880547b7afffcb3759f12f8738e2 to stable25

**Pull request merged**
