### PR TITLE
Fix docker container for local cypress tests

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/text/pull/2481#issuecomment-1155445476
* Target version: master 

### Summary
Ensure correct file permissions after bind-mount, so that nextcloud can be installed without errors.
See referenced issue comment.

### CODE REVIEW

**Comment by vinicius73** [comment]
I like how better is this test now @susnux 
It is running for me.

```
Docker version 20.10.15, build fd82621d35
Docker Compose version 2.5.0
```

**Comment by susnux** [comment]
Rebased the branch, the branch now is mergeable again.

**Review by vinicius73 — APPROVED** [review]

**Comment by juliushaertl** [comment]
@max-nextcloud Do you want to look into the manual backport or shall we skip it?

**Comment by max-nextcloud** [comment]
Let's skip it. Most dev happens on main branch anyway - some on stable25 - but I think stable24 is already rarely used for dev.

**Pull request merged**
