### PR TITLE
Fix hard line breaks displayed with additional new line between

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #3370
* Target version: master 

### Summary
To preserve soft breaks within markdown files we preserve all whitespaces, so we must not introduce additional new lines after `<br>` elements.

### CODE REVIEW

**Comment by max-nextcloud** [comment]
Looks like the common mark specs expect a newline after a `<br />` tag. The approach here seems fine - but i wonder how / if we can keep the specs.

I wonder if we could still keep this and use some css or so to ignore / remove the extra blank line.

**Comment by juliushaertl** [comment]
Thanks again for the fix @susnux 

It would be great to have a test case for this case

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
