### PR TITLE
feat: add tests for mentions

### PR DESCRIPTION
**Pull request by luka-nextcloud**
Signed-off-by: Luka Trovic <luka@nextcloud.com>

* Resolves: #2840 
* Target version: master

### CODE REVIEW

**Comment by juliushaertl** [comment]
Failures seem unrelated. @luka-nextcloud can you rebase the branch to latest master?

**Review by mejo- — APPROVED** [review]

**Comment by mejo-** [comment]
/backport 9d053cf205fedbe7d23b4e6ddacfc985411cf6bf to stable25

**Pull request merged**
