### PR TITLE
Some Design fixes

### PR DESCRIPTION
**Pull request by szaimen**
## Desktop
| Before | After |
|---|---|
| image | image |

## Mobile (iPhone 5s display)
| Before | After |
|---|---|
| image | image |

## Mobile (Google Pixel 2 display)
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by Pytal — COMMENTED** [review]
Can we get a before and after :)

**Comment by szaimen** [comment]
> Can we get a before and after :)

Updated the initial comment :)

**Review by nimisha-vijay — APPROVED** [review]

**Comment by szaimen** [comment]
Right, then I am not bothering to backport to stable20 and stable21

**Pull request merged**
