### PR TITLE
[stable26] fix(SyncService): handle failing connection gracefully

### PR DESCRIPTION
**Pull request by juliushaertl**
Backporting this specific commit to avoid random failures of cypress in https://github.com/nextcloud/text/pull/4990/files#diff-103df33bb085aaec0d6134982c312e96ecf58cf09335b9cf15964e17a45b4071R114

Signed-off-by: Max <max@nextcloud.com>

### 📝 Summary

* Resolves: # 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by mejo- — APPROVED** [review]

**Comment by juliushaertl** [comment]
Waiting with merge due to rc phase of stable26

**Comment by mejo-** [comment]
> Waiting with merge due to rc phase of stable26

Hu, are we in RC phase for stable26 already?

**Comment by juliushaertl** [comment]
Yep, somehow thought I'd have seen the rc pr already merged, nevermind

**Pull request merged**
