### PR TITLE
Don't apply author annotations when in composition

### PR DESCRIPTION
**Pull request by mejo-**
When typing dead keys (like diacritics), the browser is in composition mode[1] until the accompanioning character is typed. This breaks author annotations.

We have to hold back the transaction when in composition and only apply it afterwards, as suggested at [2]. So check for `view.composing` before applying the transaction.

Fixes: #2871

[1] https://w3c.github.io/uievents/#events-compositionevents  
[2] https://discuss.prosemirror.net/t/plugins-and-characters-with-a-diacritic/2674/3

Signed-off-by: Jonas <jonas@freesources.org>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by mejo-** [comment]
Maybe it would be good to have tests for this to prevent regressions. Probably needs an e2e cypress test. Would be curious if you think it's testable in jest.

**Comment by juliushaertl** [comment]
Might not even be testable in cypress if using a chromium based browser. Iirc firefox introduced a slightly different handling of compose keys.

**Comment by max-nextcloud** [comment]
I checked and the issue only seems to occure in firefox. So yes... will be hard to test in chrome.

**Comment by max-nextcloud** [comment]
Also had a brief look at tiptap tests and prosemirror tests.

**Tiptap** runs all tests in cypress - but sometimes they are just plain js tests.
You could create an editor with the user color extension and then try to test that directly. But i don't know how to get the editor into composition mode.
You could also try and get a hold of the apply function of the Prosemirror plugin and somehow inject a stub for the editorview. But that will only unit test the function itself. If the composition behavior of the browsers change we will not notice.

**Prosemirror** has an explicit test for composition: https://github.com/ProseMirror/prosemirror-view/blob/master/test/webtest-composition.ts
However that seems pretty hard to mimic as it uses it's own testing toolset etc.

So i don't see a way of testing this right now that would be somewhat reasonable to achieve.

**Pull request merged**
