### PR TITLE
cleanup: remove confusing paragraph button

### PR DESCRIPTION
**Pull request by azul**
The paragraph button was confusing for a number of reasons:
 * it only acts on headings
 * the symbol indicates a line break
   rather than the removal of formatting
 * there are other ways to turn headings back to normal text
 * all other formatting is removed
   by clicking the same button again

* Resolves: #353 
* Target version: master 

### Summary

See #353 for the discussion leading to this pull request.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Sounds good! :)

As said in the chat too, this needs the heading action menu (the dropdown trigger) to be highlighted too when you selected a heading so you see what to open to deselect the formatting again.

**Comment by asaage** [comment]
> there are other ways to turn headings back to normal text

@azul how would i do that now?
I've copy&pasted text from an arbitary Website and headings are carried over as such.
I really can't find a way to turn them into normal text.

**Comment by susnux** [comment]
@asaage 
 > I really can't find a way to turn them into normal text.

Just select the heading and click on the heading button again (e.g. `click: heading 1` will make the text a heading of level 1, clicking the button again makes it normal text again):
Create heading and revert to normal text again

**Comment by jancborchardt** [comment]
@asaage @susnux in a design review we also found that it’s confusing how to go back to normal formatting. We will add back a "Body text" entry in that menu, see https://github.com/nextcloud/text/issues/2836

> Add a separate item in the heading menu "Body text" as the first item (but still only show dot indicator when any heading level is selected)

**Pull request merged**
