### PR TITLE
[stable22] Fix scss deprecated syntax

### PR DESCRIPTION
**Pull request by eneiluj**
This makes the compilation fail in some contexts.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Pushed a commit as the package.json allowed using node 16 and then there is no prebuilt libsass available for that node version and the compile command fails with that. Remaining question is why the local build is different from the one in the Node CI / build action, but we can try to compare when the compile action commited the expected result. Let's see

**Comment by juliushaertl** [comment]
At least CI is stable with that but the local build is still different even with the exact same node/npm versions.  Not sure why though, the diff is rather odd with just some mapping hash changes it seems, using `git diff --text --word-diff=porcelain --word-diff-regex=.`

**Review by mejo- — APPROVED** [review]

**Pull request merged**
