### PR TITLE
Encode file to UTF-8 on `fetch` call

### PR DESCRIPTION
**Pull request by Raudius**
### Summary

Makes sure the text file is the correct (UTF-8) encoding when being retrieved through the `fetch` call

### CODE REVIEW

**Comment by juliushaertl** [comment]
@Raudius Is this ready for review?

**Comment by Raudius** [comment]
> @Raudius Is this ready for review?

Yes! Thanks for the reminder :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
