### PR TITLE
[stable24] fix: Fetch attachment share permissions

### PR DESCRIPTION
**Pull request by juliushaertl**
Backport of #4481

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
There seems to be some compat issues with Guzzle https://github.com/nextcloud/text/actions/runs/5524518111/jobs/10076930887?pr=4490 on first sight

**Comment by juliushaertl** [comment]
Definitely odd, I also see this locally, but the issues seem to be there already just considered as suppressed on the stable24 branch

`composer run psalm -- --no-cache --threads=8 --show-info=true` already shows them on the base branch. Probably a psalm bug, let me add the guzzle classes to suppress for this one.

**Comment by juliushaertl** [comment]
Damn, I accidentially pushed cea136549 to stable24 directly 🙈 Let me rebase this one

**Pull request merged**
