### PR TITLE
Increase idle timeout to one day (1440 minutes)

### PR DESCRIPTION
**Pull request by mejo-**
Signed-off-by: Jonas <jonas@freesources.org>

### 📝 Summary

As discussed, let's change the session idle timeout to 1 day.

Related to #1715.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

### CODE REVIEW

**Comment by juliushaertl** [comment]
We could also consider bumping https://github.com/nextcloud/text/blob/d8e4490db81318eaca8da50e304e5a23f8db4adb/lib/Service/SessionService.php#L39 so that sessions are also kept if someone has a network disconnect for longer than 5 minutes.

**Comment by mejo-** [comment]
/backport 8c9eaf47b45d3c65f417d0353a5cadf67e7886fd to stable25

**Comment by mejo-** [comment]
> We could also consider bumping
> 
> https://github.com/nextcloud/text/blob/d8e4490db81318eaca8da50e304e5a23f8db4adb/lib/Service/SessionService.php#L39
> so that sessions are also kept if someone has a network disconnect for longer than 5 minutes.

Good idea. What do you think would be a sensible value? Also a day? Or maybe shorter because catching up with a session after one day would not be a good idea? So maybe three hours?

**Comment by fwsmit** [comment]
Sorry to jump in at a merged PR, but I noticed you haven't finished discussing the session timeout. I think it's best to leave the session timeout this way and make sure the session can reconnect automatically if the network is restored.
I'm not that knowledgeable about this app, but a session timeout of 3 hours doesn't seem helpful and can only cause bugs.

**Pull request merged**
