### PR TITLE
fix: use php 8.1 as that is required now

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

* Resolves: CI failures such as https://github.com/nextcloud/text/actions/runs/3785280725

### CODE REVIEW

**Comment by max-nextcloud** [comment]
I think current master is segfaulting with php 7.4, 8.0 and 8.1.

I'll try to spin up a current master in my local dev env.

**Comment by max-nextcloud** [comment]
> I'll try to spin up a current master in my local dev env.

That worked fine :thinking:

**Comment by max-nextcloud** [comment]
* c31e0e3f45ce5fd70d4f74b8cb7a0a0a445ad5a3 was the server commit of the last CI run that succeeded.
* b90ccaac0f7abe85be3f4efa974d96296c3a250f was the first that [failed](https://github.com/nextcloud/text/actions/runs/3788367003/jobs/6441119649).

**Comment by juliushaertl** [comment]
Closing as the server PR was reverted

**Pull request closed without merging**
