### PR TITLE
Use slug package to make anchor more idiom and emoji compatible

### PR DESCRIPTION
**Pull request by vinicius73**
Use [slug](https://www.npmjs.com/package/slug) to improve the compatibility and consistence of heading anchors.

### CODE REVIEW

**Review by mejo- — APPROVED** [review]
Thanks @vinicius73 :heart:

**Review by juliushaertl — APPROVED** [review]

**Comment by vinicius73** [comment]
/backport 75ef911f97ec71a60312a1a5325999af60b18f2e,13ddcb95d77c941253b79dd2b43ff8fa9796f478 to stable25

**Pull request merged**
