### PR TITLE
fix line-through selector

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by szaimen** [comment]
/backport 321f030e14f0ecdb934fc6ec20de1241373b4b68 to stable27

**Review by st3iny — APPROVED** [review]
:elephant:

**Comment by szaimen** [comment]
/backport 9250ef812f72ed01e979323ad09f3d22671a0eff to stable27

**Comment by szaimen** [comment]
Cypress failure unrelated afaics...

**Comment by juliushaertl** [comment]
main should hopefully pass now again, rebased to have another run ;)

**Review by susnux — APPROVED** [review]

**Pull request merged**
