### PR TITLE
fix: adjust margin for hr

### PR DESCRIPTION
**Pull request by max-nextcloud**
* Resolves: #1889
* Target version: master 

## Before: 
Bildschirmfoto vom 2022-10-18 08-01-43

## After:
Bildschirmfoto vom 2022-10-18 08-02-27

### CODE REVIEW

**Comment by max-nextcloud** [comment]
I don't have much of an opinion on this. The `3em` spacing was confusing people as they thought it added an additional line:
https://help.nextcloud.com/t/extra-lines-inserted-after-adding-hard-line-after-update-to-nc-22/124692/2

So I think `2em` still provides enough separation while it's harder to be confused with empty lines.

**Review by juliushaertl — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Yep, 2em is all good as also commented on the issue. :) Thanks!

**Pull request merged**
