### PR TITLE
Fixes focus handling in MenuBar

### PR DESCRIPTION
**Pull request by Raudius**
* Target version: `stable24`

### Summary
Fixes an bug where the menu bar would not correctly toggle in the RichWorkspace

The root of the issue was a computed property on an injected property. Because injected properties are not reactive, this didnt work correctly.

Note: this issue is already fixed on master via: https://github.com/nextcloud/text/pull/2907

### CODE REVIEW

**Comment by mejo-** [comment]
Works like a charm, thanks @Raudius!

**Review by mejo- — APPROVED** [review]

**Comment by juliushaertl** [comment]
/backport 90752050248665cea6be4274c353b54adbea0567 to stable23

**Pull request merged**
