### PR TITLE
Rich workspace polishing

### PR DESCRIPTION
**Pull request by juliushaertl**
- Fix menu bar popover positioning (https://github.com/nextcloud/server/issues/18494)
- Fix checkbox toggle behavior (https://github.com/nextcloud/text/issues/452)
  - Checklists work but you first have to make a list, THEN make it a checklist
  - Make sure that only a click on the checkbox toggles the state

### CODE REVIEW

**Comment by jancborchardt** [comment]
@kesselb could you review if this fixes https://github.com/nextcloud/server/issues/18494 for you? :)

@jospoortvliet and also can you check if it fixes https://github.com/nextcloud/text/issues/452 for you? ;)

**Comment by kesselb** [comment]
> Fix menu bar popover positioning ([nextcloud/server#18494](https://github.com/nextcloud/server/issues/18494))

:+1: 

Peek 2020-01-01 20-45

1) Type some text
2) Try to select all with CTRL + A
3) See "Add link" element

**Comment by juliushaertl** [comment]
@kesselb There is no quick fix for the link popover positioning when all text is selected as the editor does not only have text selected internally but also the paragraph nodes that are wrapping around it.

**Comment by kesselb** [comment]
> @kesselb There is no quick fix for the link popover positioning when all text is selected as the editor does not only have text selected internally but also the paragraph nodes that are wrapping around it.

OK. I was more confused about the button shown then the wrong position.

**Pull request merged**
