### PR TITLE
Prevent dangling debounced extractHeadings function

### PR DESCRIPTION
**Pull request by mejo-**
### 📝 Summary

Our Tiptap heading extension registers a debounced extractHeadings function for onUpdate. If the editor gets removed but a debounced extractHeadings call is still pending, this leads to errors (which sometimes break tests).

So let's track whether the editor is still alive and only call debounced extractHeadings in this case.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Makes sense 👍

**Comment by max-nextcloud** [comment]
I wonder if this also applies to the other debounced functions we have. But then that's a different step / fix i guess.

**Comment by mejo-** [comment]
/backport 72a1c48ce04345a362810f7a97e022f81581093e to stable25

**Pull request merged**
