### PR TITLE
Rich workspaces: Slightly reduce vertical space

### PR DESCRIPTION
**Pull request by jancborchardt**
As discussed @karlitschek @juliushaertl @rullzer. Reduced it as much as possible with it still looking good and also that the formatting bar can just appear and not overlay any content.

## Before
Rich workspace spacing before

## After
Rich workspaces spacing after

(Also found and fixed another related small issue: fix formatting bar overlapping files controls bar.)

### CODE REVIEW

**Comment by karlitschek** [comment]
Hmmm. Still pushes the files list a lot down. Maybe make it even smaller? Maybe a look at a folder without the file recommendations?

**Comment by jancborchardt** [comment]
Right, for a fresh folder with only files in it, there’s way too much space still. That space goes away only once you click into the rich workspaces area.

Will look into fixing that.

**Comment by rullzer** [comment]
@jancborchardt can you show it full screen?
Because on my system the recommendations are just a single line. Which gives you the filelist a lot earlier.

**Comment by jancborchardt** [comment]
Fixed it for subfolders too – @rullzer there you go without Recommendations (as they are only shown in the root folder atm)

Everything nicely aligns too, I would say this is good to go now?

## Before
Rich workspaces subfolder before

## After
Rich workspaces subfolder after

**Comment by jancborchardt** [comment]
Ah, also fixed a small issue: It created a file called "README.md" which is a bit shouty-technical. Changed to more human "Readme.md".

**Comment by jancborchardt** [comment]
I don’t understand the Drone failure … https://drone.nextcloud.com/nextcloud/text/813/6/7
I guess I need to commit the build files?

---------

@karlitschek does it look good from the screenshots at https://github.com/nextcloud/text/pull/468#issuecomment-563900985

**Comment by karlitschek** [comment]
@jancborchardt definitely better. We can see how it feels in real and see how it looks

**Comment by skjnldsv** [comment]
@rullzer I win by 4 seconds

**Comment by ChristophWurst** [comment]
actually I won because I got to click the green button

**Comment by jancborchardt** [comment]
I win cause my name is on the commit?

**Comment by ChristophWurst** [comment]
:cry:

**Comment by jancborchardt** [comment]
Actually @juliushaertl wins cause he both coded this awesome feature _and_ he is on vacation atm!

**Pull request merged**
