### PR TITLE
l10n: Correct spelling

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Review by vinicius73 — APPROVED** [review]

**Comment by Valdnet** [comment]
Please merge 😉.

**Comment by juliushaertl** [comment]
This is not present in 24 ;)

**Pull request merged**
