### PR TITLE
Fix link menu positioning

### PR DESCRIPTION
**Pull request by juliushaertl**
### Summary

Fixes some styling issues with the menu bubble positioning and giving it a fixed height of 44px since it otherwise would change height when switching to the link input. 

I'm not entirely sure about the 44px height since it looks kind of huge compared to the rest, but for now I picked this since those are buttons and we have a minimum click target of 44px

#### Before
image

#### After
image

### Notes for backporting 

:warning: When backporting we need to specify an additional fixed width for this since tiptap doesn't handle resizing the menu bubble properly. With Nextcloud < 20 the single button is smaller than the input which caused that the input could be cut of due do missing repositioning. A width of 180px seems to be fine as a fix for older versions for this.

### CODE REVIEW

**Review by azul — APPROVED** [review]
Looks good to me. I had a look both at the code and tested it (rebased on current master) locally. The height change makes sense to me.

I was not able to reproduce the alignment issue discussed in #600 - with current master. 
Maybe this has already been fixed. The changes in here do not seem to target it anyway. Just the branch name made me read the bug description and see if it had any effect.

**Comment by juliushaertl** [comment]
> I was not able to reproduce the alignment issue discussed in #600 - with current master.

Yeah #600 was somehow mitigated on master/stable20 since with the two buttons the initial width of the button container was higher, therefore the initial position calculations work better when switching to the input for links.

**Review by jancborchardt — APPROVED** [review]
Looks good! Would be even better with white background for the menu and the divider in color-border, but we can also do that separately. :)

**Comment by jancborchardt** [comment]
@juliushaertl needs rebase, but then let’s get it in? :)

**Comment by juliushaertl** [comment]
Rebased and also added a design fix as discussed in our call: 
image

**Comment by MorrisJobke** [comment]
🙄

**Pull request merged**
