### PR TITLE
Fix mention uid autocomplete and keyboard handler in list nodes

### PR DESCRIPTION
**Pull request by juliushaertl**
- Register default extensions first
- Mentions: Also search for user id in the current active sessions

### 📝 Summary

* Resolves: #3451

The mentions plugin was not catching the keyboard events when being triggered in a list/todo item, so I moved the registration of optional plugins for the editor after the default ones, which seems to fix the issue (as found in https://github.com/ueberdosis/tiptap/issues/3339)

In addition the autocomplete endpoint for mentions now also filters by user id when iterating over the active user sessions.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/master/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by marcelklehr — APPROVED** [review]
Looks good

**Review by mejo- — APPROVED** [review]
Looks good to me :)

**Comment by mejo-** [comment]
/backport bef86e9de24c122ff09ee241208cdababc6e3713,daa717d39232998c83c25c2b19bf8b27c98e15e3 to stable25

**Comment by nickvergessen** [comment]
Thanks a lot :)

**Pull request merged**
