### PR TITLE
Bump @nextcloud/vue to 6.0.0-beta.1

### PR DESCRIPTION
**Pull request by juliushaertl**
Still throwing some errors in the viewer as https://github.com/nextcloud/viewer/pull/1319 / https://github.com/nextcloud/viewer/pull/1300 are missing and the Vue instance has a different version there.

Ref https://github.com/vuejs/vue/issues/12627

At some point we should probably rethink our way of embedding text in viewer to avoid version dependencies like that.

### CODE REVIEW

**Comment by PVince81** [comment]
obsoleted by https://github.com/nextcloud/server/pull/33508

**Comment by vinicius73** [comment]
viewer has been updated to vue 2.7

https://github.com/nextcloud/viewer/pull/1300

There no more errors like https://github.com/vuejs/vue/issues/12627

**Comment by vinicius73** [comment]
I just found a style error, it seems to work correctly.

The main problem is the new popover component (floating-vue).
There are some behavior making the tests do not work anymore.

I will send a PR to nextcloud-vue to address some of that behaviors.

**Comment by juliushaertl** [comment]
@vinicius73 I pushed an adjustment to the cypress selectors and it seems to be happy about that. Also ran another smoke test an couldn't find any obvious issues. Maybe you can later list your findings, so we have that tracked.

Voting for getting this in fast, we can still follow up on smaller issues.

**Review by Raudius — APPROVED** [review]
Tested against server master branch, working well! :)

**Comment by juliushaertl** [comment]
- [ ] Check issues mentioned by Vincent in https://github.com/nextcloud/server/pull/33516 regarding the focus-trap in actions

**Pull request merged**
