### PR TITLE
Set #content margin to 0 for direct editing

### PR DESCRIPTION
**Pull request by mejo-**
`#content` has a default margin in Nextcloud 25, which breaks the layout for direct editing. Manually set it to 0 in order to fix direct editing.

Fixes: #2976

Signed-off-by: Jonas <jonas@freesources.org>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by mejo-** [comment]
@juliushaertl this removes the blue borders in direct editing view (#2976), but I have no idea whether it also fixes direct editing in mobile clients (#3121). Could you test this locally to see whether it solves the issue for you?

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
/backport ba1bc2cb2eef697252fa98b89b8d8321beda91d4 to stable25

**Pull request merged**
