### PR TITLE
Fix alignment and design of checkboxes

### PR DESCRIPTION
**Pull request by jancborchardt**
As discussed @juliushaertl – also found some more stuff than just the alignment of the checkbox. :) 

Before | After
-|-
checkboxes before|Checkboxes after

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Very nice Jan! I can't test but the css looks sane.

**Comment by juliushaertl** [comment]
Looks much nicer, one small suggestion, how about also adjusting the regular lists, so that the bullet points are centered to the checkboxes?

image

**Comment by rullzer** [comment]
master is 21.

**Comment by jancborchardt** [comment]
> Looks much nicer, one small suggestion, how about also adjusting the regular lists, so that the bullet points are centered to the checkboxes?
> 
> image

I would agree, however this is not possible without hacking one way or the other:
https://stackoverflow.com/questions/4373046/css-control-space-between-bullet-and-li

And this is something which – if at all – we should do separately. :) In the usual cases, bulleted lists and task lists might not immediately follow each other, so it’s not so bad for now.

**Review by juliushaertl — APPROVED** [review]

**Review by eneiluj — APPROVED** [review]
Super nice

**Pull request merged**
