### PR TITLE
Support underline - use `__underlined__` in markdown

### PR DESCRIPTION
**Pull request by azul**
* Resolves: #75
* Target version: master 

### Summary

Underlines are not supported in commonmark markdown. So we need our own way of encoding them. Tripple `_` means double `_` plus single `_` - so bold AND italic in most markdown editors. So use quadrupple `_` instead.

Only available with `Ctrl + u` keyboard shortcut for now. Maybe that's enough as we don't want to encorage underline anyway.

### CODE REVIEW

**Comment by eneiluj** [comment]
Nice!

So how do we let users know how to underline things? Why not adding a button in the menubar? In other words, why don't we encourage underlining?

Quadruple underscore won't be recognized as underline in any other markdown renderers. Are we ok with that?

**Comment by azul** [comment]
@eneiluj I think one reason not to encourage it is the second point you brought up. It's not supported by other markdown things. Also most designers i talked to don't like underlining text. It's harder to read and does not add meaning unless it's in a specific context like medicine.

My reasoning for now would be if people ask for underline we can tell them the keyboard combination. If people paste underlined text it will be preserved. From my point of view that solves the main use cases. But I'd be okay with adding a button - maybe below the bold button like a menu to not make the toolbar even wider.

Is there any underline syntax that other markdown editors understand?

**Comment by azul** [comment]
Looks like some use `++underline++` and some use `__underline__`. We currently convert `__hello__` to `**hello**` when loading the markdown in the editor. I would like to preserve the original markdown as much as possible.

Markdown has emphasis and strong emphasis. Most of the time emphasis is rendered as italics and strong emphasis is rendered as bold. I'm not sure about having two different ways to do strong emphasis based on what chars were used might be confusing with other editors that display both as the same.

**Comment by juliushaertl** [comment]
> My reasoning for now would be if people ask for underline we can tell them the keyboard combination. If people paste underlined text it will be preserved. From my point of view that solves the main use cases. But I'd be okay with adding a button - maybe below the bold button like a menu to not make the toolbar even wider.

I'd agree on not having a button there. @jancborchardt What do you think?

> Looks like some use ++underline++ and some use `__underline__`. We currently convert __hello__ to **hello** when loading the markdown in the editor. I would like to preserve the original markdown as much as possible.
> Markdown has emphasis and strong emphasis. Most of the time emphasis is rendered as italics and strong emphasis is rendered as bold. I'm not sure about having two different ways to do strong emphasis based on what chars were used might be confusing with other editors that display both as the same.

Preserving the original markdown is actually a strong argument of just using __underline__ for this i think. That I totally missed in the previous discussion in the issue. This would mean we just render the two usages of emphasis differently depending on their source.

**Comment by mejo-** [comment]
Great work, I like :blush: 

Though I'm not sure about the decision to not expose underlining in the menubar. In my opinion, hiding features and only making them available to "power users" is kind of an anti-pattern.

Also, in case you go with exposing it in the menubar, mentioning the keyboard shortcut in the tooltip would be super nice :blush:

**Comment by jancborchardt** [comment]
> Though I'm not sure about the decision to not expose underlining in the menubar. In my opinion, hiding features and only making them available to "power users" is kind of an anti-pattern.

Yup, agree with that @mejo- – especially since to anyone who doesn’t know Markdown (a.k.a. majority of people ;), underlining is super normal, we should have it in the bar. The common order is: Bold, Italic, Underline, Strikethrough.

(A more likely candidate for hiding would be "Strikethrough" btw, which neither Google Docs nor Office 365 shows by default in the bar. But since we don’t have a menu bar, it’s fine to keep it.)

**Review by juliushaertl — APPROVED** [review]
Lets stick with the 4 underscores which in common mark would just be rendered as strong and we don't interfere with other syntax then

**Comment by juliushaertl** [comment]
@azul I took the opportunity and added the menu item right away when testing it. Would be good to go from my side.

**Review by juliushaertl — CHANGES_REQUESTED** [review]
Sorry, blocking again, tired to add a test case and it indeed is an issue with reading the file from markdown as we use markdown-it for that which converts `____test____` to `<b>test</b>`

**Comment by juliushaertl** [comment]
We could probably introduce something similar to this for handling that https://github.com/outline/rich-markdown-editor/blob/f31ab5c0af38c7c1170c1c5328f5f8140673c674/src/rules/underlines.ts

**Comment by mejo-** [comment]
Would be nice to get this added to the formatting help modal as well: https://github.com/nextcloud/text/blob/master/src/components/HelpModal.vue

**Comment by max-nextcloud** [comment]
> Sorry, blocking again, tired to add a test case and it indeed is an issue with reading the file from markdown as we use markdown-it for that which converts `____test____` to `<b>test</b>`

I ended up going with the double `_` for underline. Seemed better than introducing a completely different syntax than everyone else. I also considered just using `<u>underlined</u>` - which would be the common mark compatible approach. But then we do not allow html in markdown and working around was less obvious - still might be an option though.

Benefits of just using `__`:
* more consistent with `**` from a users perspective
* keeps previously used markdown intact (does not change `__` to `**`).
* easier to type and more consistent as a shortcut.

So for tests i simply reused the common mark tests modifying the expected tag from `strong` to `u` if the markdown contained `__`. There were no tests mixing `__` and `**` - so for now it's working fine.

**Pull request merged**
