### PR TITLE
Harden check when using token from memcache

### PR DESCRIPTION
**Pull request by rullzer**
Explicitly comparing never hurt anybody.

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Session cache is only available starting with Nextcloud 19 https://github.com/nextcloud/text/pull/761

**Comment by juliushaertl** [comment]
@rullzer It might make sense to also backport that one, any opinions?

**Comment by MorrisJobke** [comment]
> @rullzer It might make sense to also backport that one, any opinions?

🙄

**Comment by juliushaertl** [comment]
Not urgently needed, so I'd say we skip this for now.

**Pull request merged**
