### PR TITLE
fix(session): Fix setting a guest name

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #4252

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]

**Comment by max-nextcloud** [comment]
We should really have a cypress test for this as it's something we do not often test during our daily routine.

**Comment by mejo-** [comment]
> We should really have a cypress test for this as it's something we do not often test during our daily routine.

Agreed, added one now.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
