### PR TITLE
[stable24] Fix npm audit

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated fix of npm audit

### CODE REVIEW

**Comment by mejo-** [comment]
`stable24` is end of life. I opened https://github.com/nextcloud/text/pull/4311 to prevent updates to `stable24`.

**Comment by juliushaertl** [comment]
Damn, let me check locally what is going wrong there

**Comment by juliushaertl** [comment]
Seems totally fine locally:

```

up to date, audited 1591 packages in 3s

182 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

@szaimen Have you seen something like this since you worked on the github action for updating the audit fix?

Let me close this for now.

**Comment by szaimen** [comment]
> @szaimen Have you seen something like this since you worked on the github action for updating the audit fix?

No, not yet

**Pull request closed without merging**
