### PR TITLE
fix: Properly emit ready event on conflicts with the editor API

### PR DESCRIPTION
**Pull request by juliushaertl**
### 📝 Summary

* Resolves: https://github.com/nextcloud/notes/issues/1008

Fixes loading the editor integrated through the editor API when a file conflict occurs during the initial loading. In this case the ready event was never emitted on the root component that would pass the state to the notes app.

I'd love to have a more generic way there but haven't found a proper way to avoid emitting on both this and parent, so the second commit cleans up the emit handling in Editor.vue to make sure we always emit on both.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Also fixes this issue on Collectives as there the parent component is the `ViewerComponent`

**Review by mejo- — APPROVED** [review]
Thanks for tackeling this @juliushaertl. Code looks good to me :+1:

**Pull request merged**
