### PR TITLE
Fix cypress tests

### PR DESCRIPTION
**Pull request by eneiluj**
Tests are no longer passing with server master.

### CODE REVIEW

**Comment by vinicius73** [comment]
It is related to #2345
refs: 
https://github.com/nextcloud/server/issues/32060
https://github.com/nextcloud/server/pull/32326

**Comment by eneiluj** [comment]
@vinicius73 Ok let's see if tests pass again once Text is using material design icons.

Let's keep this PR open in case we temporarily need it to make it easier to merge other PRs :grin:.

**Comment by max-nextcloud** [comment]
https://github.com/nextcloud/text/actions/runs/2332794337 looks like test are passing again on master.

**Comment by eneiluj** [comment]
@max-nextcloud Thanks for mentioning this here.

**Pull request closed without merging**
