### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#lt_LT/text/178591509
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rakekniven Mind to remove the whitespace to just fix the missing r ?

**Comment by rakekniven** [comment]
My research with leo and deepl was before creating this PR. Wondering about the different definitions... will adapt PR

**Comment by juliushaertl** [comment]
stable17: Included the commit in https://github.com/nextcloud/text/pull/193

**Comment by jancborchardt** [comment]
@rakekniven no worries! :) Thanks a lot for the fix, as no one noticed the missing r before. :D

**Pull request merged**
