### PR TITLE
Use GH ref as cypress run title

### PR DESCRIPTION
**Pull request by skjnldsv**
image

### CODE REVIEW

**Comment by juliushaertl** [comment]
Failure unrelated

**Comment by juliushaertl** [comment]
Oh I see, it would be rather this one then or?

https://github.com/nextcloud/viewer/blob/master/.github/workflows/cypress.yml#L82

**Comment by skjnldsv** [comment]
Ah, I added the type of PR, push or pull, but not the title! :rocket: 
Thanks Julius :)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/text/pull/3473

**Pull request merged**
