### PR TITLE
Use full list of supported filenames when obtaining the name to create

### PR DESCRIPTION
**Pull request by juliushaertl**
This makes sure that newly created files use the translation of "Readme.md" and the translated files are properly picked up for opening.

cc @jancborchardt

### CODE REVIEW

**Comment by gary-kim** [comment]
I thought the file name for new files was on the client side. This is the file I patch for my instance.
https://github.com/nextcloud/text/blob/732da03d72fb2e20d4c9b666a5d2c0709213d011/src/views/RichWorkspace.vue#L152
Sorry, I might be misunderstanding something.

**Comment by juliushaertl** [comment]
Ah, indeed, why did we have this in multiple places :see_no_evil: 

Let me see if we can reuse the workspace ocs api for that as well.

**Comment by juliushaertl** [comment]
Let's get this in first then and fix the javascript case in a follow up.

**Pull request merged**
