### PR TITLE
Fix rich workspaces on folders without create permissions

### PR DESCRIPTION
**Pull request by danxuliu**
The workspace placeholder is shown if there is no _Readme.md_ file in the folder and invites the user to add some text, which (tries to) create the _Readme.md_ file. Therefore, if the user does not have create permissions on the folder the placeholder should not be shown.

Besides that rich workspaces are explicitly disabled in public share pages. Before `RichWorkspaceEnabled` was not defined, so although the rich workspaces were not shown an error appeared in the browser console [when trying to access that value](https://github.com/nextcloud/text/blob/6c13c8bc5f76e57461d903da5cde5d37ae14ff33/src/views/RichWorkspace.vue#L75).

Although the RichWorkspace view [seems to be explicitly loaded in public file lists](https://github.com/nextcloud/text/blob/b21f51cfd53ef999dda967292e7f1c5a31edf033/src/helpers/files.js#L177)... so maybe it would be better to enable it instead of disable it (but it would require adjusting the value returned by [the controller](https://github.com/nextcloud/text/blob/61297bdd83745214162aa5384009cfdf2b631ece/lib/Controller/WorkspaceController.php#L142) like done in this pull request for registered users so the rich workspace is disabled when creating files is not allowed in the public folder).

## How to test
- Create a folder
- Share the folder with another user
- Disable create permissions on the share
- Log in as the other user
- Open the shared folder

### Result with this pull request

The rich workspace placeholder is not shown.

### Result without this pull request

The rich workspace placeholder is shown. Clicking on it shows a _Could not create file_ error.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Pushed another commit to actually expose the workspace_available value on public shares to fix https://github.com/nextcloud/text/issues/729 and https://github.com/nextcloud/text/issues/716

**Comment by danxuliu** [comment]
> Pushed another commit to actually expose the workspace_available value on public shares to fix #729 and #716

Note that [the controller for public folders](https://github.com/nextcloud/text/blob/ba44d7b587af90d7335d341b55c44938e273fb24/lib/Controller/WorkspaceController.php#L157-L167) needs to return the permissions of the folder for the current user/guest in order to allow creation of the readme.md file in public folders (although if the file is there already it will be editable if the folder allows it, even if the permissions are not sent, it is justs for creation).

**Comment by kaystrobach** [comment]
will that be backported to v18 or just available for v19?

**Comment by danxuliu** [comment]
Yes, it will be backported to v18, but #759 needs to be merged first :-)

**Pull request merged**
