### PR TITLE
fix(build): without non deterministic vendor-LICENSE.txt

### PR DESCRIPTION
**Pull request by max-nextcloud**
The content of `vendor.LICENSE.txt` is not deterministic.

If two versions of one library are imported
one of them will be picked and listed in the file.

This results in arbitrary changes to the file
which in turn create npm fix audit PRs such as #6534.

See also: https://nextcloud-libraries.github.io/nextcloud-vite-config/interfaces/BaseOptions.html#thirdPartyLicense

### CODE REVIEW

**Comment by juliushaertl** [comment]
I think we added that on purpose for compliance reasons, but I'm unsure what the current state there is.

activity for example also has this disabled and a separate flag but commented out: https://github.com/nextcloud/activity/blame/master/vite.config.ts#L16-L18

@susnux Any hint there? Is this fine to turn off for now?

**Comment by susnux** [comment]
It is ok to do so, but instead enabled `extractLicenseInformation` to keep us compliant.

**Comment by juliusknorr** [comment]
@max-nextcloud Can you adjust that?

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Needs changes

**Comment by max-nextcloud** [comment]
> @max-nextcloud Can you adjust that?

Done. Added `extractLicenseInformation: true`.

**Review by juliusknorr — APPROVED** [review]

**Comment by juliusknorr** [comment]
@max-nextcloud I think this broke reuse compliance, can you check that? Seems it only happend on main as the committed assets were only updated there.

**Comment by max-nextcloud** [comment]
@juliusknorr ahh... I was wondering what broke it. I'll take a look

**Comment by juliusknorr** [comment]
Please remove the backport-request label if you manually backported :)

**Pull request merged**
