### PR TITLE
Simplify save indicator

### PR DESCRIPTION
**Pull request by juliushaertl**
Some fixes from the design review in https://github.com/nextcloud/text/issues/1075

Based on #1296 

- Simplify save indicator to Saving/Saved
- Add some space to the menu bar so that button circles do no longer look cut off
- ~Add disabled styling for undo/redo buttons~ Needed to revert this since it had a major performance impact and requires more investigation
- Add improved indicator for active styling
- Show full menubar on public share links (where the talk sidebar overlapped before)
- Simplify wording
- Add spacing to color annotations

### CODE REVIEW

**Comment by juliushaertl** [comment]
>  cypress: default-group — 1 test failed 

Failure from a previous run, but cypress doesn't update the state if the github action is just retriggered.

**Comment by rullzer** [comment]
For me it shows all the way to the left. Is that intented?

**Review by rullzer — APPROVED** [review]
Works as adverstied on regular md files.

**Comment by juliushaertl** [comment]
Fix for that is in https://github.com/nextcloud/text/pull/1409

**Pull request merged**
