### PR TITLE
Use `max-height` in DocumentStatus, fixes empty 50px bar above toolbar

### PR DESCRIPTION
**Pull request by mejo-**
Fixes a regression introduced by 5a2541d2e4.

2023-03-29T13:33:52,593606247+02:00

### CODE REVIEW

**Review by luka-nextcloud — APPROVED** [review]

**Comment by mejo-** [comment]
/backport 2a2b988bf0016fc0847b2d13f2bf698348a5cbcf to stable26

**Comment by mejo-** [comment]
Manually pushed 2a2b988bf0016fc0847b2d13f2bf698348a5cbcf to #3988, no backport needed anymore.

**Pull request merged**
