### PR TITLE
fix: prefix heading ids

### PR DESCRIPTION
**Pull request by snehar97**
### 📝 Summary

* Resolves: #3513
prefix heading ids to prevent naming conflicts.

#### 🖼️ Screenshots
Capture1

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by snehar97** [comment]
this pull request superseeds #3775

**Comment by mejo-** [comment]
@snehar97 what's the reason that you opened a new PR? Continueing to work in #3775 would have been fine too, no? Anyway, code looks good to me - and thanks again for looking into this :heart:

**Comment by snehar97** [comment]
> @snehar97 what's the reason that you opened a new PR? Continueing to work in #3775 would have been fine too, no?

@mejo- thats because cypress test was not passing on my fork.

**Comment by susnux** [comment]
Have you checked that at least in the files app and the collective app no elements exists that match the pattern `h-.*` ?
Because otherwise we would have an ID collision and changing the pattern again later on is really a bad thing (as explained in the other PR users would have to change all links in their markdown files / collectives).

**Comment by mejo-** [comment]
> Have you checked that at least in the files app and the collective app no elements exists that match the pattern `h-.*` ? Because otherwise we would have an ID collision and changing the pattern again later on is really a bad thing (as explained in the other PR users would have to change all links in their markdown files / collectives).

At least for the moment there doesn't seem to be an element with `id="h.*` in either Text or Collectives.

**Comment by mejo-** [comment]
> These two ids in the tests probably also need to be adjusted: https://github.com/nextcloud/text/pull/3795/files#diff-8e8d87b74c5ec8c1a4001543ef5d641a25c99122adbe8ad64be0c534a82237f2L87-L93

@snehar97 once this is addressed, the PR should be ready to be merged.

**Comment by susnux** [comment]
> At least for the moment there doesn't seem to be an element with `id="h.*` in either Text or Collectives.

:+1:
(Files is important because text is shown in the viewer, so the viewer and files app on the background are part of the dom too)

**Comment by juliushaertl** [comment]
Also didn't find any reference of `h-(.*)` as ids in checked out server and apps tree.

**Comment by snehar97** [comment]
@mejo- tests have passed now can you please check on this

**Review by mejo- — APPROVED** [review]

**Comment by mejo-** [comment]
Thanks a lot @snehar97 :heart:

**Pull request merged**
