### PR TITLE
fix: remove help entry from action list

### PR DESCRIPTION
**Pull request by vinicius73**
Regression from  #2664

- Remove formatting-help from other action list
- Isolate character count 

## After

image

## Before

image

### CODE REVIEW

**Review by mejo- — CHANGES_REQUESTED** [review]
I moved the formatting help to the action list on purpose after discussing this topic with @jancborchardt :laughing:. The idea was to always force the formatting help into the three dot menu in order to never have only word/character count there. See https://github.com/nextcloud/text/pull/2664/commits/6771397b7752e10013fc4c15d48f0001f95c7753.

What exactly are you trying to fix with this PR @vinicius73?

**Comment by vinicius73** [comment]
As you can see in the print, the formatting help wasn't only in the "three dots" menu.
It also was in the "heading menu".

I've removed it from `ActionList.vue` (who was generating this side effect)

**Review by mejo- — APPROVED** [review]
Thanks a lot, makes sense now :heart:

**Review by juliushaertl — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by mejo-** [comment]
/backport a902b89e0f0e65b9158172a8bb73755d053304dc,ee4c21ce3564efce6c735c126d19ba607eab40fd to stable25

**Pull request merged**
