### PR TITLE
[stable27] Bump @nextcloud/dialogs to 4.2.0

### PR DESCRIPTION
**Pull request by juliushaertl**

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Review by max-nextcloud — APPROVED** [review]
nice :rocket:

**Review by AndyScherzinger — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failures are only related to changes in selectors that are used for tests, can adapt shortly but would also be fine to merge and follow up

**Comment by juliushaertl** [comment]
Fix pushed, passing fine locally now.

**Comment by juliushaertl** [comment]
Cannot figure out why local node build differs, let's use the one compiled by the action

**Pull request merged**
