### PR TITLE
fix: update ImageView

### PR DESCRIPTION
**Pull request by luka-nextcloud**
### 📝 Summary

* Resolves: #4045

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [ ] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Review by max-nextcloud — APPROVED** [review]
I wonder why `@blur` did not do the trick. But this also seems fine.

**Comment by juliushaertl** [comment]
The `@blur` seems to work just fine, however I noticed that the actual issue seems to be that the component might be re-rendered if the user moves the mouse out which then restores the old value even before the blur was triggered

https://github.com/nextcloud/text/blob/5730fc775d0aa3927ce5b4fd07f23f3c3b7be454/src/nodes/ImageView.vue#L32

Anyways I think always updating seems more safe to me 👍

**Review by juliushaertl — APPROVED** [review]

**Comment by max-nextcloud** [comment]
shall we backport this?

**Comment by juliushaertl** [comment]
@luka-nextcloud Please backport manually.

**Pull request merged**
